// ============================================================================
// BLOG_POST_META — SSR truth table for EN blog posts (extracted from
// render/index.ts per SEO-04 so it is a pure data module importable by
// tests and, per SEO-02, replaceable by manifest-derived generation).
// Missing entry = Googlebot/Bingbot get 404 for that slug.
// ============================================================================

export const BLOG_POST_META: Record<string, {
  title: string;
  description: string;
  /** PR79 Phase 2G — datePublished + image used by the BlogPosting
   *  JSON-LD so the EN side reaches schema parity with VI (which
   *  drives the fields from vi_blog_posts.published_at +
   *  cover_image_url). When a new post lands, copy the
   *  `publishedDate` + `heroImage.src` from
   *  src/content/blog/posts/<slug>.ts. Posts with empty image
   *  fall back to DEFAULT_OG_IMAGE in the renderer. */
  datePublished?: string;
  /** ai-seo review 2026-07-07 — set when an EN post gets a real content
   *  update so BlogPosting.dateModified emits a genuine freshness signal
   *  (AI engines weight recency heavily). Falls back to datePublished. */
  dateModified?: string;
  image?: string;
}> = {
  "vietnam-pickleball-players-to-watch-2026": { title: "Vietnamese Pickleball Players to Watch in 2026", description: "The Vietnamese pickleball players to watch in 2026 — Ly Hoang Nam, Truong Vinh Hien, Do Minh Quan and the rising stars chasing titles at the HCMC Open and Da Nang World Cup.", datePublished: "2026-07-15", image: "/images/blog/vietnam-pickleball-players-to-watch-2026-hero.webp" },
  "vietnam-hosts-ppa-tour-asia-2026": { title: "Vietnam Hosts PPA Tour Asia 2026: HCMC Open, World Cup Da Nang and a Historic Season", description: "In 2026 Vietnam hosts two PPA Tour Asia stops — the $300,000 MB Hanoi Cup and the HCMC Open (Aug 6–9) — plus the first Pickleball World Cup ever held in Asia (Da Nang, Aug 30–Sep 6). How Vietnam became the center of Asian pickleball.", datePublished: "2026-07-13", image: "/images/blog/vietnam-hosts-ppa-tour-asia-2026-hero.webp" },
  "pickleball-cost-vietnam-2026": { title: "How Much Does Pickleball Cost in Vietnam? The 2026 Price Guide", description: "What pickleball really costs in Vietnam in 2026: court rental by city (70,000–400,000 VND/hour), paddles from 400,000 VND, coaching, tournament entry fees, and three realistic monthly budgets — plus how to play for less.", datePublished: "2026-07-11", image: "/images/blog/pickleball-cost-vietnam-2026-hero.webp" },
  "hcmc-open-2026-preview": { title: "HCMC Open 2026 Preview: The PPA Asia 500 Comes to Ho Chi Minh City", description: "The MB Ho Chi Minh City Open lands Aug 6\u20139, 2026 at Global City Sports Park \u2014 a US$70,000, 500-point PPA Tour Asia stop. Dates, venue, full prize breakdown, amateur registration, and how to watch.", datePublished: "2026-07-10", image: "/images/blog/hcmc-open-2026-preview-hero.webp" },
  "ppa-beijing-open-2026-recap": { title: "PPA Beijing Open 2026 Recap: Vietnam's Hien & Quan Win Men's Doubles Gold", description: "Truong Vinh Hien and Do Minh Quan won men's doubles gold at the PPA Asia 500 Beijing Open 2026, beating Miyoshi/Stirling 11-9, 11-7. Full results, the road to the final, Vinh Hien's singles bronze, and the Ly Hoang Nam withdrawal.", datePublished: "2026-06-23", image: "/images/blog/ppa-beijing-open-2026-recap-hero.webp" },
  "vietnam-pickleball-tournament-calendar-2026": { title: "Vietnam Pickleball Tournament Calendar 2026: Every Major Event", description: "The complete 2026 pickleball tournament calendar for Vietnam — the Ho Chi Minh City Open (Aug 6–9), the Pickleball World Cup in Da Nang (Aug 30–Sep 6), the full PPA Tour Asia schedule, and domestic events. Dates, venues, prize money.", datePublished: "2026-07-06", image: "/images/blog/vietnam-pickleball-tournament-calendar-2026-hero.webp" },
  "pickleball-club-management-software-comparison": { title: "Best Pickleball Club Management Software in 2026 — Honest Comparison", description: "Compare the best pickleball club management software in 2026 — CourtReserve, Playtomic, PlayByPoint, ClubSpark, Pickle Planner and more. Features, pricing, and a realistic low-cost stack for Vietnamese clubs.", datePublished: "2026-06-15" , image: "/images/blog/pickleball-club-management-software-comparison-hero.webp"},
  "pickleball-tournament-budget-calculator-guide": { title: "Pickleball Tournament Budget: Full Cost Breakdown, Templates & Free Calculator (2026)", description: "How much does it cost to run a pickleball tournament? Full 2026 cost breakdown in USD and VND, 3 ready budget templates, a break-even entry fee formula, and a free spreadsheet.", datePublished: "2026-06-13" , image: "/images/blog/pickleball-tournament-budget-calculator-guide-hero.webp"},
  "ppa-tour-asia-2026-recap": { title: "PPA Tour Asia 2026: Mid-Season Recap & Results So Far", description: "PPA Tour Asia 2026 recap: 3 of 10 stops done — Ly Hoang Nam's historic Hanoi title, Vietnam's Hien Truong winning in KL, Tama's Macao double, and the road to the $1.1M Hong Kong Slam.", datePublished: "2026-06-11", image: "/images/blog/ppa-tour-asia-2026-recap-hero.webp" },
  "mlp-vs-ppa-2026-which-tour-to-watch": { title: "MLP vs PPA 2026: Which Pickleball Tour Should You Watch?", description: "MLP and PPA merged under the UPA in 2024 but keep different formats. A 2026 guide to which pro pickleball tour to watch — plus PPA Tour Asia's Vietnam stops.", datePublished: "2026-06-09", image: "/images/blog/mlp-vs-ppa-2026-which-tour-to-watch-hero.webp" },
  "vietnam-pickleball-federation-2026": { title: "Is There a Vietnam Pickleball Federation? 2026 Status & Roadmap", description: "No national pickleball federation exists in Vietnam yet (mid-2026) — only an organizing committee approved Sept 2025. The full status: roadmap, city-level federations, and what 2026 changes.", datePublished: "2026-06-08", image: "/images/blog/vietnam-pickleball-federation-2026-hero.webp" },
  "pickleball-erne-shot-tutorial": { title: "The Erne in Pickleball: How to Hit It, Rules & Setup (2026)", description: "The pickleball erne explained: what it is, why it's legal, jump vs stationary erne, step-by-step technique, how to set it up, defense, mistakes, and drills.", datePublished: "2026-06-05", image: "/images/blog/pickleball-erne-shot-tutorial-hero.webp" },
  "pickleball-doubles-stacking-strategy": { title: "Pickleball Stacking Strategy: A Complete Doubles Guide (2026)", description: "Pickleball stacking explained: what it is, how to stack on the serve and return, the lefty-righty stack, hand signals, full vs half stack, mistakes, and drills.", datePublished: "2026-06-03", image: "/images/blog/pickleball-doubles-stacking-strategy-hero.webp" },
  "pickleball-third-shot-drop-vs-drive": { title: "Third Shot Drop vs Drive in Pickleball: Which to Hit & When (2026)", description: "Third shot drop vs drive in pickleball: what each shot does, the mechanics, when to drop, when to drive, the hybrid drive-and-drop, common mistakes, and drills.", datePublished: "2026-06-01", image: "/images/blog/pickleball-third-shot-drop-vs-drive-hero.webp" },
  "pickleball-dink-technique-mastery": { title: "How to Dink in Pickleball: Technique Mastery Guide 2026", description: "Master the pickleball dink: grip, paddle face, contact point, cross-court vs straight, topspin dink, the 5 most common mistakes, and 4 drills to practice.", datePublished: "2026-06-01", image: "/images/blog/pickleball-dink-technique-mastery-hero.webp" },
  "dupr-thepicklehub-user-guide": { title: "DUPR on ThePickleHub: Complete User Guide 2026 — Connect, Log Matches, Rankings", description: "Connect DUPR to ThePickleHub in one click, log matches with opponent confirmation, submit to DUPR, and track your rating on the Vietnam DUPR leaderboard.", datePublished: "2026-05-29", image: "/images/blog/dupr-thepicklehub-user-guide-hero.webp" },
  "pickleball-court-dimensions-setup-guide": { title: "Pickleball Court Dimensions & Setup Guide 2026 | Sizes + Diagram", description: "Official pickleball court dimensions: 44×20 ft playing area, 7 ft kitchen, net height, total space needed. Plus how to mark a court and convert a tennis court.", datePublished: "2026-05-29", image: "/images/blog/pickleball-court-dimensions-setup-guide-hero.webp" },
  "pickleball-vs-padel-vs-paddle-tennis": { title: "Pickleball vs Padel vs Paddle Tennis: Complete Guide 2026", description: "Pickleball vs padel vs paddle tennis: full 2026 comparison of court size, rules, scoring, equipment, where each sport is popular, what to try first.", datePublished: "2026-05-26", image: "/images/blog/pickleball-vs-padel-vs-paddle-tennis-hero.webp" },
  "best-pickleball-paddles-beginners-2026": { title: "Best Pickleball Paddles for Beginners 2026: 7 Top Picks (Asia Buyer's Guide)", description: "Picking your first pickleball paddle without overspending. 7 beginner-friendly paddles for 2026 with weight, face, grip specs — plus what to avoid in VN.", datePublished: "2026-05-24", image: "/images/blog/best-pickleball-paddles-beginners-2026-hero.webp" },
  "pickleball-for-tennis-players-2026": { title: "Pickleball for Tennis Players: 5 Things to Unlearn (2026 Guide)", description: "Tennis players struggle with pickleball not because it's harder — they bring 5 ingrained habits that backfire. Here's what to unlearn and the 7-day fix.", datePublished: "2026-05-22", image: "/images/blog/pickleball-for-tennis-players-2026-hero.webp" },
  "vietnam-dupr-leaderboard-launch": { title: "Vietnam DUPR Leaderboard | Live Pickleball Rankings on ThePickleHub", description: "ThePickleHub now hosts a live Vietnam DUPR pickleball leaderboard updated by webhook. Plus DUPR-required tournaments, auto-seeded brackets, and balanced Mexicano pairings.", datePublished: "2026-05-27", image: "/images/blog/vietnam-dupr-leaderboard-launch-hero.webp" },
  "dupr-rating-improvement-30-day-plan": { title: "Improve DUPR Rating in 30 Days | Realistic Training Plan 2026", description: "A 30-day plan to raise your DUPR rating: how DUPR's algorithm rewards consistent play, the 4 rules from Part 2, and a week-by-week training schedule.", datePublished: "2026-05-20", image: "/images/blog/dupr-rating-improvement-30-day-plan-hero.webp" },
  "professional-pickleball-tours-guide-2026": { title: "Pro Pickleball Tours 2026 | PPA vs MLP vs APP vs PPA Asia Compared", description: "2026 guide to pro pickleball tours: PPA Tour, MLP, PPA Tour Asia, APP — schedules, prize money, formats, top players, how to watch from Asia.", datePublished: "2026-05-18", image: "/images/blog/professional-pickleball-tours-guide-2026-hero.webp" },
  "dupr-algorithm-explained-performance-vs-expectation": { title: "DUPR Algorithm Explained 2025: Why You Lose Points After Winning | Part 2 of 3", description: "DUPR's July 2025 algorithm: why winning can lose points and losing can gain them. Match weights, exclusion rules, reliability score. Part 2 of 3.", datePublished: "2026-05-14", image: "/images/blog/dupr-algorithm-performance-vs-expectation-hero.webp" },
  "tama-shimabukuro-ppa-atlanta-final-15-year-old": { title: "Tama Shimabukuro Reaches PPA Atlanta Final at 15 | Beats Hunter Johnson & Staksrud", description: "15-year-old Tama Shimabukuro beat world #1 Hunter Johnson and #2 Staksrud at PPA Atlanta Championships to reach the final. Self-taught Hawaii story.", datePublished: "2026-05-11", image: "/images/blog/tama-shimabukuro-atlanta-hero.webp" },
  "what-is-dupr-pickleball-rating-system": { title: "What Is DUPR? Pickleball Rating System Explained | Part 1 of 3 Series", description: "DUPR explained: the global pickleball rating used by PPA, MLP, USA Pickleball, World Cup. How it works, who runs it, why Vietnamese players need it.", datePublished: "2026-05-11", image: "/images/blog/dupr-pickleball-rating-hero.webp" },
  "dupr-vietnam-partnership-ta-pickleball-thepicklehub": { title: "DUPR Vietnam Partnership Announced | TA Pickleball x ThePickleHub First Step", description: "DUPR, TA Pickleball and ThePickleHub signed a preliminary deal to bring the global pickleball rating system to Vietnam — phase 1 of a 3-phase roadmap.", datePublished: "2026-05-13", image: "/images/blog/dupr-ta-picklehub-partnership-hero.webp" },
  "pickleball-tour-wars-2023-explained": { title: "Pickleball Tour Wars 2023 Explained | 10 Days That Changed Pro Pickleball", description: "Pickleball Tour Wars 2023: how PPA and MLP fought for 10 days, why Gold Contracts only exist from that window, and what it means for Vietnamese pros today.", datePublished: "2026-05-05", image: "/images/blog/pickleball-tour-wars-2023-hero.webp" },
  "app-tour-vs-ppa-tour-contracts-2026": { title: "APP Tour vs PPA Tour 2026 | Contracts, Money & Exclusivity Compared", description: "APP Tour vs PPA Tour 2026: contract structures, prize money, exclusivity, the Global Pickleball Alliance, and Quang Duong's APP deal explained.", datePublished: "2026-05-05", image: "/images/blog/app-tour-vs-ppa-tour-contracts-hero.webp" },
  "pickleball-world-cup-2026-da-nang": { title: "Pickleball World Cup 2026 Da Nang | Dates, Teams, Venues, How to Watch", description: "Pickleball World Cup 2026 in Da Nang, Vietnam (Aug 30–Sep 6). Up to 80 nations, 4,000 athletes. Dates, venues, format, Vietnam team.", datePublished: "2026-04-23", dateModified: "2026-07-16", image: "/images/blog/pickleball-world-cup-2026-da-nang-hero.webp" },
  "how-to-watch-ppa-tour-live-2026": { title: "How to Watch PPA Tour Live 2026 | Streaming Platforms, Schedules & Free Options", description: "Watch PPA Tour live in 2026 on PBTV, Amazon Prime, CBS, ESPN, and Fox Sports. Plus free YouTube highlights + ThePickleHub livestreams.", datePublished: "2026-04-16", image: "/images/blog/how-to-watch-ppa-tour-live-2026-hero.webp?v=2" },
  "ppa-tour-asia-2026-complete-guide": { title: "PPA Tour Asia 2026: Complete Schedule, Prize Money & How to Play", description: "PPA Tour Asia 2026 complete guide — 10 tournament stops in Vietnam, Japan, Korea, Thailand. Schedule, prize money, registration, live streams.", datePublished: "2026-04-16", image: "/images/blog/ppa-tour-asia-2026-hero.webp" },
  "best-pickleball-tournament-software-2026": { title: "Best Pickleball Tournament Software 2026", description: "Compare the best pickleball tournament software in 2026: free bracket generators, round robin tools, MLP team match platforms. No signup.", datePublished: "2025-12-15" },
  "how-to-create-pickleball-bracket": { title: "How to Create a Pickleball Bracket", description: "How to create a pickleball bracket for round robin, single elimination, and double elimination — with a free bracket generator + live scoring.", datePublished: "2025-11-20" },
  "pickleball-round-robin-generator-guide": { title: "Pickleball Round Robin Generator Guide 2026", description: "Free pickleball round robin generator with auto scheduling, court rotation, and live scoring. Organize a perfect round robin tournament.", datePublished: "2025-10-10" },
  "pickleball-scoring-rules-guide": { title: "Pickleball Scoring Rules 2026 | Beginner Guide", description: "Learn pickleball scoring rules for singles, doubles, and tournament play. Rally scoring vs side-out explained. Free digital scoring tool included.", datePublished: "2026-03-15" },
  "how-to-organize-pickleball-tournament": { title: "How to Organize a Pickleball Tournament 2026", description: "Step-by-step guide to organize a pickleball tournament: venue, format, registration, scheduling, scoring, and free tools to run the event.", datePublished: "2026-03-20" },
  "pickleball-doubles-strategy-guide": { title: "Pickleball Doubles Strategy & Tips 2026", description: "Pickleball doubles strategy for tournaments: partner communication, court positioning, stacking, and when to attack the kitchen line.", datePublished: "2026-03-22" },
  "pickleball-tournament-formats-explained": { title: "Pickleball Tournament Formats | Round Robin & More", description: "Pickleball tournament formats explained: round robin, single + double elimination, MLP team match, flex. Choose the right format for your event.", datePublished: "2026-03-25" },
  "pickleball-live-streaming-guide": { title: "Pickleball Live Streaming Guide 2026", description: "Watch pickleball live streams for free. Learn how to stream your own pickleball tournament online with The Pickle Hub's free livestreaming platform.", datePublished: "2026-03-29" },
  "mlp-format-explained": { title: "MLP Format Explained 2026 | Major League Pickleball", description: "MLP format explained: Major League Pickleball team match rules, dreambreaker, lineup strategy, and how to organize your own MLP-style event.", datePublished: "2026-03-29" },
  "free-pickleball-bracket-generator": { title: "Free Pickleball Bracket Generator 2026", description: "Free pickleball bracket generator: round robin, single + double elimination, with real-time scoring. Build a tournament bracket in 60 seconds.", datePublished: "2026-03-29" },
  "pickleball-bracket-templates": { title: "Pickleball Bracket Templates 2026 | Free Download", description: "Free pickleball bracket templates for round robin, single + double elimination. Sizes for 4, 8, 16, 32, 64 players with live scoring.", datePublished: "2026-03-29" },
  "pickleball-rules-complete-guide": { title: "Pickleball Rules 2026 | Complete Guide with Asia's Hardest Calls Explained", description: "The 2026 pickleball rulebook simplified: serve, two-bounce, kitchen/NVZ, scoring, faults. Plus 5 disputed calls in Asian tournaments.", datePublished: "2026-04-19" },
  "tournament-organizer-hub": { title: "Pickleball Tournament Organizer Hub | Formats, Brackets, Tools 2026", description: "Pickleball tournament organizer hub 2026: choose a format, build brackets, manage scoring, livestream, and compare free software — all from one page.", datePublished: "2026-04-25", image: "/images/blog/tournament-organizer-hub-hero.webp" },
  "how-to-play-pickleball": { title: "How to Play Pickleball | 7-Day Beginner Plan Tested in Vietnam", description: "How to play pickleball: beginner gear, grip, 6 core shots, and a 7-day practice plan tested with 200+ Vietnamese players. Start playing in week one.", datePublished: "2026-04-26", image: "/images/blog/how-to-play-pickleball-hero.webp" },
};
