import type { BlogPostMetadata } from "./types";

/**
 * Lightweight blog post metadata — imported by list pages
 * (Blog index, home blog section) so we don't pull in full post
 * sections/FAQs (~10-25KB per post) when rendering cards.
 *
 * Generated from src/content/blog/posts/*.ts — keep in sync when
 * adding/editing posts.
 */
export const blogMetadata: BlogPostMetadata[] = [
  {
    slug: "tournament-organizer-hub",
    publishedDate: "2026-04-25",
    updatedDate: "2026-04-25",
    author: "The PickleHub Team",
    tags: ["organize", "tournament", "hub", "guide", "directory"],
    ctaPath: "/tools",
    ctaLabel: { en: "Open Free Tournament Tools", vi: "Mở công cụ tổ chức miễn phí" },
    heroImage: {
      src: "/images/blog/tournament-organizer-hub-hero.webp",
      alt: "Pickleball tournament organizer hub — workflow from format selection through bracket generation, scoring, livestream, and software comparison"
    },
    titleEn: "Pickleball Tournament Organizer Hub — Every Guide, Tool & Format in One Place",
    titleVi: "Hub Tổ chức giải Pickleball — Mọi hướng dẫn, công cụ và thể thức trong một trang",
    metaTitleEn: "Pickleball Tournament Organizer Hub | Formats, Brackets, Tools 2026",
    metaTitleVi: "Hub Tổ chức giải Pickleball | Thể thức, Bracket, Công cụ 2026",
    metaDescriptionEn: "The complete hub for pickleball tournament organizers in 2026. Choose a format, build a bracket, manage scoring, livestream matches, and compare free software — all linked from one page.",
    metaDescriptionVi: "Hub đầy đủ cho ban tổ chức giải pickleball 2026. Chọn thể thức, tạo bracket, quản lý điểm, livestream và so sánh phần mềm miễn phí — tất cả liên kết trong một trang.",
  },  {
    slug: "pickleball-world-cup-2026-da-nang",
    publishedDate: "2026-04-23",
    updatedDate: "2026-04-23",
    author: "The PickleHub Team",
    tags: ["world cup pickleball", "da nang", "vietnam", "tournament", "asia", "2026", "guide"],
    ctaPath: "/tournaments",
    ctaLabel: { en: "Browse Tournaments", vi: "Xem các giải đấu" },
    heroImage: {
      src: "/images/blog/pickleball-world-cup-2026-da-nang-hero.webp",
      alt: "Pickleball World Cup 2026 in Da Nang, Vietnam — Aug 30 to Sep 6, 2026, Tien Son Sports Palace, ~80 countries and 4,000 athletes"
    },
    titleEn: "Pickleball World Cup 2026 in Da Nang, Vietnam — Complete Guide",
    titleVi: "World Cup Pickleball 2026 tại Đà Nẵng — Hướng dẫn đầy đủ",
    metaTitleEn: "Pickleball World Cup 2026 Da Nang | Dates, Teams, Venues, How to Watch",
    metaTitleVi: "World Cup Pickleball 2026 Đà Nẵng | Lịch thi đấu, Đội tuyển, Cách xem",
    metaDescriptionEn: "Pickleball World Cup 2026 comes to Da Nang, Vietnam (Aug 30 – Sep 6). Up to 80 nations and 4,000 athletes. Dates, venues, format, Vietnam team — complete guide.",
    metaDescriptionVi: "Đà Nẵng đăng cai World Cup Pickleball 2026 từ 30/8 – 6/9. Gần 80 quốc gia, 4.000 VĐV. Lịch thi đấu, địa điểm, đội tuyển Việt Nam — thông tin đầy đủ.",
  },  {
    slug: "best-pickleball-tournament-software-2026",
    publishedDate: "2025-12-15",
    updatedDate: "2026-03-27",
    author: "The PickleHub Team",
    tags: ["tournament", "software", "comparison"],
    ctaPath: "/tools",
    ctaLabel: { en: "Try Free Tournament Tools", vi: "Dùng thử miễn phí" },
    heroImage: undefined,
    titleEn: "Best Pickleball Tournament Software in 2026 — Free Tools Compared",
    titleVi: "Phần mềm tổ chức giải Pickleball tốt nhất 2026 — So sánh công cụ miễn phí",
    metaTitleEn: "Best Pickleball Tournament Software 2026 | Free Bracket Tools Compared",
    metaTitleVi: "Phần mềm tổ chức giải Pickleball tốt nhất 2026 | So sánh công cụ tạo bracket miễn phí",
    metaDescriptionEn: "Compare the best pickleball tournament software in 2026. Free bracket generators, round robin tools, and MLP team match platforms for organizers. No signup required.",
    metaDescriptionVi: "So sánh phần mềm tổ chức giải pickleball tốt nhất 2026. Tạo bracket miễn phí, round robin, MLP team match cho ban tổ chức. Không cần đăng ký.",
  },  {
    slug: "free-pickleball-bracket-generator",
    publishedDate: "2026-03-29",
    updatedDate: "2026-03-29",
    author: "The PickleHub Team",
    tags: ["bracket", "generator", "free", "tool"],
    ctaPath: "/tools/quick-tables",
    ctaLabel: { en: "Create Free Bracket Now", vi: "Tạo bracket miễn phí ngay" },
    heroImage: undefined,
    titleEn: "Free Pickleball Bracket Generator — Create Tournament Brackets in 60 Seconds",
    titleVi: "Tạo Bracket Pickleball miễn phí — Bracket giải đấu trong 60 giây",
    metaTitleEn: "Free Pickleball Bracket Generator 2026 | Create Brackets in 60 Seconds",
    metaTitleVi: "Tạo Bracket Pickleball miễn phí 2026 | Tạo bracket trong 60 giây",
    metaDescriptionEn: "Create free pickleball tournament brackets instantly. Round robin, single elimination, and double elimination bracket generator with real-time scoring. No signup required.",
    metaDescriptionVi: "Tạo bracket giải pickleball miễn phí tức thì. Vòng tròn, loại trực tiếp, loại kép với chấm điểm realtime. Không cần đăng ký.",
  },  {
    slug: "how-to-create-pickleball-bracket",
    publishedDate: "2025-11-20",
    updatedDate: "2026-03-27",
    author: "The PickleHub Team",
    tags: ["bracket", "guide", "round-robin"],
    ctaPath: "/tools/quick-tables",
    ctaLabel: { en: "Create Your Bracket Now", vi: "Tạo bracket ngay" },
    heroImage: undefined,
    titleEn: "How to Create a Pickleball Bracket — Step-by-Step Guide",
    titleVi: "Cách tạo Bracket giải Pickleball — Hướng dẫn từng bước",
    metaTitleEn: "How to Create a Pickleball Bracket | Free Step-by-Step Guide 2026",
    metaTitleVi: "Cách tạo Bracket giải Pickleball | Hướng dẫn miễn phí 2026",
    metaDescriptionEn: "Learn how to create a pickleball bracket for round robin, single elimination, and double elimination tournaments. Free bracket generator with real-time scoring.",
    metaDescriptionVi: "Hướng dẫn tạo bracket giải pickleball cho vòng tròn, loại trực tiếp, và loại kép. Công cụ tạo bracket miễn phí với chấm điểm realtime.",
  },  {
    slug: "how-to-organize-pickleball-tournament",
    publishedDate: "2026-03-20",
    updatedDate: "2026-03-29",
    author: "The PickleHub Team",
    tags: ["organize", "tournament", "guide"],
    ctaPath: "/tools",
    ctaLabel: { en: "Start Organizing Now", vi: "Bắt đầu tổ chức ngay" },
    heroImage: undefined,
    titleEn: "How to Organize a Pickleball Tournament — The Complete Organizer's Checklist",
    titleVi: "Cách tổ chức giải đấu Pickleball — Checklist đầy đủ cho ban tổ chức",
    metaTitleEn: "How to Organize a Pickleball Tournament | Complete Checklist 2026",
    metaTitleVi: "Cách tổ chức giải Pickleball | Checklist đầy đủ 2026",
    metaDescriptionEn: "Step-by-step guide to organizing a pickleball tournament. Venue, format selection, registration, scheduling, scoring, and free tools. Everything you need to run a successful event.",
    metaDescriptionVi: "Hướng dẫn từng bước tổ chức giải pickleball. Địa điểm, thể thức, đăng ký, lịch thi đấu, chấm điểm, và công cụ miễn phí. Mọi thứ bạn cần để chạy giải thành công.",
  },  {
    slug: "how-to-watch-ppa-tour-live-2026",
    publishedDate: "2026-04-16",
    updatedDate: "2026-04-16",
    author: "The PickleHub Team",
    tags: ["ppa tour", "live streaming", "watch live", "pickleball tv", "2026"],
    ctaPath: "/live",
    ctaLabel: { en: "Watch Free Tournaments", vi: "Xem giải đấu miễn phí" },
    heroImage: { src: "/images/blog/how-to-watch-ppa-tour-live-2026-hero.webp?v=2", alt: "PPA Tour professional pickleball match being broadcast live with multiple camera angles and streaming overlay" },
    titleEn: "How to Watch PPA Tour Live in 2026 — Every Streaming Platform & Free Options",
    titleVi: "Cách Xem PPA Tour Trực Tiếp Năm 2026 — Tất Cả Nền Tảng & Tùy Chọn Miễn Phí",
    metaTitleEn: "How to Watch PPA Tour Live 2026 | Streaming Platforms, Schedules & Free Options",
    metaTitleVi: "Xem PPA Tour Trực Tiếp 2026 | Nền Tảng, Lịch Trình & Tùy Chọn Miễn Phí",
    metaDescriptionEn: "Watch PPA Tour live in 2026 on PBTV, Amazon Prime, CBS Sports, ESPN, and Fox Sports. Free YouTube highlights and ThePickleHub's free tournament livestreams included.",
    metaDescriptionVi: "Xem PPA Tour trực tiếp năm 2026 trên PBTV, Amazon Prime, CBS Sports, ESPN và Fox Sports. Bao gồm highlights YouTube miễn phí và livestream miễn phí từ ThePickleHub.",
  },  {
    slug: "mlp-format-explained",
    publishedDate: "2026-03-29",
    updatedDate: "2026-03-29",
    author: "The PickleHub Team",
    tags: ["mlp", "team-match", "format", "rules"],
    ctaPath: "/tools/team-match",
    ctaLabel: { en: "Create MLP Team Match", vi: "Tạo giải đồng đội MLP" },
    heroImage: undefined,
    titleEn: "MLP Format Explained — Major League Pickleball Team Match Rules & How to Play",
    titleVi: "Thể thức MLP giải thích — Luật thi đấu đồng đội Major League Pickleball",
    metaTitleEn: "MLP Format Explained 2026 | Major League Pickleball Rules & Team Match Guide",
    metaTitleVi: "Thể thức MLP Pickleball 2026 | Luật đồng đội Major League Pickleball",
    metaDescriptionEn: "Learn how the MLP format works in pickleball. Complete guide to Major League Pickleball team match rules, dreambreaker, lineup strategy, and how to organize your own MLP-style event.",
    metaDescriptionVi: "Tìm hiểu thể thức MLP trong pickleball. Hướng dẫn đầy đủ về luật thi đấu đồng đội Major League Pickleball, dreambreaker, chiến thuật lineup.",
  },  {
    slug: "pickleball-bracket-templates",
    publishedDate: "2026-03-29",
    updatedDate: "2026-03-29",
    author: "The PickleHub Team",
    tags: ["bracket", "template", "tournament"],
    ctaPath: "/tools/quick-tables",
    ctaLabel: { en: "Use Free Bracket Template", vi: "Dùng mẫu bracket miễn phí" },
    heroImage: undefined,
    titleEn: "Pickleball Bracket Templates — Free Templates for Every Tournament Format",
    titleVi: "Mẫu Bracket Pickleball — Mẫu miễn phí cho mọi thể thức giải đấu",
    metaTitleEn: "Pickleball Bracket Templates 2026 | Free Download for 4-64 Players",
    metaTitleVi: "Mẫu Bracket Pickleball 2026 | Miễn phí cho 4-64 người chơi",
    metaDescriptionEn: "Free pickleball bracket templates for round robin, single elimination, and double elimination. Templates for 4, 8, 16, 32, and 64 players with real-time scoring.",
    metaDescriptionVi: "Mẫu bracket pickleball miễn phí cho vòng tròn, loại trực tiếp, và loại kép. Mẫu cho 4, 8, 16, 32, và 64 người chơi với chấm điểm realtime.",
  },  {
    slug: "pickleball-doubles-strategy-guide",
    publishedDate: "2026-03-22",
    updatedDate: "2026-03-29",
    author: "The PickleHub Team",
    tags: ["doubles", "strategy", "tips"],
    ctaPath: "/tools/doubles-elimination",
    ctaLabel: { en: "Create Doubles Bracket", vi: "Tạo bracket đôi" },
    heroImage: undefined,
    titleEn: "Pickleball Doubles Strategy — Winning Tips for Tournament Players",
    titleVi: "Chiến thuật Pickleball đôi — Mẹo thắng cho người chơi giải đấu",
    metaTitleEn: "Pickleball Doubles Strategy & Tips | Tournament Winning Guide 2026",
    metaTitleVi: "Chiến thuật Pickleball đôi | Mẹo thắng giải 2026",
    metaDescriptionEn: "Master pickleball doubles strategy for tournaments. Partner communication, court positioning, stacking, and when to attack the kitchen. Improve your doubles game today.",
    metaDescriptionVi: "Nắm vững chiến thuật pickleball đôi cho giải đấu. Giao tiếp đồng đội, vị trí sân, stacking, và khi nào tấn công kitchen. Cải thiện game đôi ngay hôm nay.",
  },  {
    slug: "pickleball-live-streaming-guide",
    publishedDate: "2026-03-29",
    updatedDate: "2026-03-29",
    author: "The PickleHub Team",
    tags: ["livestream", "streaming", "guide"],
    ctaPath: "/live",
    ctaLabel: { en: "Watch Live Now", vi: "Xem trực tiếp ngay" },
    heroImage: undefined,
    titleEn: "Pickleball Live Streaming — How to Watch & Stream Pickleball Online",
    titleVi: "Trực tiếp Pickleball — Cách xem và phát sóng trực tuyến",
    metaTitleEn: "Pickleball Live Streaming 2026 | How to Watch & Stream Online Free",
    metaTitleVi: "Xem trực tiếp Pickleball 2026 | Hướng dẫn phát sóng và xem miễn phí",
    metaDescriptionEn: "Watch pickleball live streams for free. Learn how to stream your own pickleball tournament online with The Pickle Hub's free livestreaming platform.",
    metaDescriptionVi: "Xem trực tiếp pickleball miễn phí. Hướng dẫn phát sóng giải đấu pickleball trực tuyến với nền tảng livestream miễn phí của The Pickle Hub.",
  },  {
    slug: "pickleball-round-robin-generator-guide",
    publishedDate: "2025-10-10",
    updatedDate: "2026-03-27",
    author: "The PickleHub Team",
    tags: ["round-robin", "generator", "tutorial"],
    ctaPath: "/tools/quick-tables",
    ctaLabel: { en: "Generate Round Robin Now", vi: "Tạo vòng tròn ngay" },
    heroImage: undefined,
    titleEn: "Pickleball Round Robin Generator — How to Run the Perfect Round Robin Tournament",
    titleVi: "Công cụ tạo vòng tròn Pickleball — Cách tổ chức giải vòng tròn hoàn hảo",
    metaTitleEn: "Pickleball Round Robin Generator | Free Tool & Complete Guide 2026",
    metaTitleVi: "Công cụ tạo vòng tròn Pickleball | Miễn phí & Hướng dẫn đầy đủ 2026",
    metaDescriptionEn: "Free pickleball round robin generator with automatic scheduling, court rotation, and live scoring. Learn how to organize the perfect round robin tournament.",
    metaDescriptionVi: "Công cụ tạo vòng tròn pickleball miễn phí với lịch tự động, xoay sân, và chấm điểm trực tiếp. Hướng dẫn tổ chức giải vòng tròn hoàn hảo.",
  },  {
    slug: "pickleball-rules-complete-guide",
    publishedDate: "2026-04-19",
    updatedDate: "2026-04-19",
    author: "Cuong Nguyen",
    tags: ["pickleball rules", "beginner", "kitchen rule", "serving", "scoring", "ppa tour asia"],
    ctaPath: "/tools/quick-tables",
    ctaLabel: { en: "Try Free Scoring Tool", vi: "Dùng thử chấm điểm miễn phí" },
    heroImage: { src: "/images/blog/pickleball-rules-complete-guide-hero.webp", alt: "Pickleball court with players at the kitchen line showing the Non-Volley Zone and serving positions under PPA Tour Asia rules" },
    titleEn: "Pickleball Rules 2026: The Complete Guide (With Asia's Hardest Calls Explained)",
    titleVi: "Luật Pickleball 2026 — Hướng dẫn đầy đủ (kèm 5 tình huống tranh cãi nhất ở châu Á)",
    metaTitleEn: "Pickleball Rules 2026 | Complete Guide with Asia's Hardest Calls Explained",
    metaTitleVi: "Luật Pickleball 2026 | Hướng dẫn đầy đủ và 5 tình huống tranh cãi nhất ở châu Á",
    metaDescriptionEn: "The complete 2026 Pickleball rulebook simplified: serve, two-bounce, kitchen/NVZ, scoring, faults. Plus: the 5 calls that start fights in Asian tournaments — and how to settle them.",
    metaDescriptionVi: "Luật Pickleball 2026 đầy đủ: giao bóng, luật hai lần nảy, kitchen/NVZ, tính điểm, lỗi. Kèm 5 tình huống gây tranh cãi nhất ở các giải châu Á và cách xử lý đúng luật.",
  },  {
    slug: "pickleball-scoring-rules-guide",
    publishedDate: "2026-03-15",
    updatedDate: "2026-03-29",
    author: "The PickleHub Team",
    tags: ["scoring", "rules", "beginner"],
    ctaPath: "/tools/quick-tables",
    ctaLabel: { en: "Try Free Scoring Tool", vi: "Dùng thử chấm điểm miễn phí" },
    heroImage: undefined,
    titleEn: "Pickleball Scoring Rules Explained — Complete Guide for Beginners & Tournament Play",
    titleVi: "Luật chấm điểm Pickleball — Hướng dẫn đầy đủ cho người mới và giải đấu",
    metaTitleEn: "Pickleball Scoring Rules 2026 | Complete Beginner & Tournament Guide",
    metaTitleVi: "Luật chấm điểm Pickleball 2026 | Hướng dẫn cho người mới & giải đấu",
    metaDescriptionEn: "Learn pickleball scoring rules for singles, doubles, and tournament play. Rally scoring vs side-out explained. Free digital scoring tool included.",
    metaDescriptionVi: "Học luật chấm điểm pickleball cho đơn, đôi và giải đấu. Rally scoring vs side-out giải thích chi tiết. Công cụ chấm điểm số miễn phí.",
  },  {
    slug: "pickleball-tournament-formats-explained",
    publishedDate: "2026-03-25",
    updatedDate: "2026-03-29",
    author: "The PickleHub Team",
    tags: ["formats", "tournament", "comparison"],
    ctaPath: "/tools",
    ctaLabel: { en: "Explore All Formats", vi: "Khám phá tất cả thể thức" },
    heroImage: undefined,
    titleEn: "Pickleball Tournament Formats Explained — Which One Should You Use?",
    titleVi: "Các thể thức giải Pickleball giải thích — Nên dùng thể thức nào?",
    metaTitleEn: "Pickleball Tournament Formats Explained | Round Robin, Elimination & More",
    metaTitleVi: "Thể thức giải Pickleball giải thích | Vòng tròn, Loại trực tiếp & Khác",
    metaDescriptionEn: "Complete guide to pickleball tournament formats: round robin, single elimination, double elimination, MLP team match, and flex tournaments. Choose the right format for your event.",
    metaDescriptionVi: "Hướng dẫn đầy đủ về thể thức giải pickleball: vòng tròn, loại trực tiếp, loại kép, MLP team match, và flex tournament. Chọn đúng thể thức cho sự kiện của bạn.",
  },  {
    slug: "ppa-tour-asia-2026-complete-guide",
    publishedDate: "2026-04-16",
    updatedDate: "2026-04-16",
    author: "The PickleHub Team",
    tags: ["ppa tour asia", "tournament", "asia", "schedule", "guide"],
    ctaPath: "/tournaments",
    ctaLabel: { en: "Browse Tournaments", vi: "Xem các giải đấu" },
    heroImage: { src: "/images/blog/ppa-tour-asia-2026-hero.webp", alt: "PPA Tour Asia 2026 professional pickleball tournament with multiple courts and packed stadium" },
    titleEn: "PPA Tour Asia 2026: Complete Schedule, Prize Money & How to Play",
    titleVi: "PPA Tour Asia 2026: Lịch thi đấu, Tiền thưởng & Cách tham gia",
    metaTitleEn: "PPA Tour Asia 2026 Schedule & Guide | All 10 Stops, Prize Money, How to Play",
    metaTitleVi: "PPA Tour Asia 2026 | Lịch thi đấu đầy đủ, Tiền thưởng, Cách tham gia",
    metaDescriptionEn: "Complete guide to PPA Tour Asia 2026 — all 10 tournament stops, $2.15M total prize money, dates, cities, and how amateurs can play alongside the pros.",
    metaDescriptionVi: "Hướng dẫn đầy đủ PPA Tour Asia 2026 — 10 chặng đấu, tổng tiền thưởng $2.15 triệu, lịch trình, địa điểm và cách VĐV nghiệp dư tham gia thi đấu cùng các pro.",
  },
];

export const blogSlugs: string[] = blogMetadata.map((p) => p.slug);
