import type { BlogPostMetadata } from "./types";

/**
 * Lightweight blog post metadata — imported by list pages
 * (Blog index, home blog section) so we don't pull in full post
 * sections/FAQs (~10-25KB per post) when rendering cards.
 *
 * Generated from src/content/blog/posts/*.ts — keep in sync when
 * adding/editing posts.
 */
export const blogMetadata: BlogPostMetadata[] = [
  {
    slug: "ppa-beijing-open-2026-recap",
    publishedDate: "2026-06-23",
    updatedDate: "2026-06-23",
    author: "Cuong Nguyen",
    tags: ["ppa beijing open 2026", "beijing open pickleball", "truong vinh hien", "do minh quan", "ppa tour asia 2026", "ly hoang nam pickleball", "pickleball vietnam", "vietnamese pickleball champions"],
    ctaPath: "/blog/ppa-tour-asia-2026-complete-guide",
    ctaLabel: { en: "Next Vietnam stop: Ho Chi Minh City Open, Aug 6–9 — full schedule & prize money", vi: "Chặng Việt Nam tiếp theo: Ho Chi Minh City Open 6–9/8 — lịch & tiền thưởng" },
    titleEn: "PPA Beijing Open 2026 Recap: Vietnam's Hien & Quan Win Men's Doubles Gold",
    titleVi: "PPA Beijing Open 2026: Vinh Hiển & Minh Quân vô địch đôi nam",
    metaTitleEn: "PPA Beijing Open 2026 Recap | Vietnam Wins Men's Doubles",
    metaTitleVi: "PPA Beijing Open 2026 | Vinh Hiển, Minh Quân vô địch đôi nam",
    metaDescriptionEn: "Truong Vinh Hien and Do Minh Quan won men's doubles gold at the PPA Asia 500 Beijing Open 2026, beating Miyoshi/Stirling 11-9, 11-7. Full results, the road to the final, Vinh Hien's singles bronze, and the Ly Hoang Nam withdrawal.",
    metaDescriptionVi: "Trương Vinh Hiển và Đỗ Minh Quân vô địch đôi nam PPA Asia 500 Beijing Open 2026, thắng Miyoshi/Stirling 11-9, 11-7. Kết quả đầy đủ, đường tới chung kết, HCĐ đơn nam của Vinh Hiển và vụ Lý Hoàng Nam rút lui.",
  },
  {
    slug: "pickleball-club-management-software-comparison",
    publishedDate: "2026-06-15",
    updatedDate: "2026-06-15",
    author: "Cuong Nguyen",
    tags: ["pickleball club management software", "best pickleball club app", "pickleball court booking software", "pickleball league management", "courtreserve", "playtomic", "pickleball club software", "pickleball vietnam"],
    ctaPath: "/tools",
    ctaLabel: { en: "Run Your Club's Tournaments Free", vi: "Tổ chức giải cho CLB miễn phí" },
    heroImage: { src: "/images/blog/pickleball-club-management-software-comparison-hero.webp", alt: "Laptop and smartphone displaying a pickleball club management dashboard with a member list, court-booking calendar and payment-status badges, beside a paddle and ball on a minimalist desk." },
    titleEn: "Best Pickleball Club Management Software in 2026 — Honest Comparison",
    titleVi: "Phần Mềm Quản Lý CLB Pickleball Tốt Nhất 2026 — So Sánh Thẳng Thắn",
    metaTitleEn: "Best Pickleball Club Management Software 2026 | Compared",
    metaTitleVi: "Phần Mềm Quản Lý CLB Pickleball 2026 | So Sánh Chi Tiết",
    metaDescriptionEn: "Compare the best pickleball club management software in 2026 — CourtReserve, Playtomic, PlayByPoint, ClubSpark, Pickle Planner and more. Features, pricing, and a realistic low-cost stack for Vietnamese clubs.",
    metaDescriptionVi: "So sánh phần mềm quản lý CLB pickleball tốt nhất 2026 — CourtReserve, Playtomic, PlayByPoint, ClubSpark, Pickle Planner. Tính năng, giá, và bộ công cụ miễn phí thực tế cho CLB Việt Nam.",
  },
  {
    slug: "pickleball-tournament-budget-calculator-guide",
    publishedDate: "2026-06-13",
    updatedDate: "2026-06-13",
    author: "Cuong Nguyen",
    tags: ["pickleball tournament budget", "pickleball tournament cost", "how much does a pickleball tournament cost", "tournament budget template", "pickleball entry fee", "tournament organizer", "pickleball vietnam"],
    ctaPath: "/tools",
    ctaLabel: { en: "Create Free Tournament Brackets with Bracket Lab", vi: "Tạo bracket giải đấu miễn phí với Bracket Lab" },
    heroImage: { src: "/images/blog/pickleball-tournament-budget-calculator-guide-hero.webp", alt: "Flat-lay of a pickleball tournament organizer's desk with a laptop showing a budget spreadsheet, calculator, notebook, paddle and pickleballs." },
    titleEn: "Pickleball Tournament Budget: Full Cost Breakdown, Templates & Free Calculator (2026)",
    titleVi: "Tổ Chức Giải Pickleball Tốn Bao Nhiêu? Dự Toán Chi Tiết + File Mẫu Miễn Phí (2026)",
    metaTitleEn: "Pickleball Tournament Budget 2026 | Costs + Free Template",
    metaTitleVi: "Dự Toán Ngân Sách Giải Pickleball 2026 | Chi Phí + File Mẫu",
    metaDescriptionEn: "How much does it cost to run a pickleball tournament? Full 2026 cost breakdown in USD and VND, 3 ready budget templates, a break-even entry fee formula, and a free spreadsheet.",
    metaDescriptionVi: "Tổ chức một giải pickleball tốn bao nhiêu tiền? Bảng chi phí 2026 chi tiết bằng VNĐ và USD, 3 mẫu ngân sách giải nhỏ/vừa/lớn, công thức tính lệ phí hòa vốn, kèm file Excel miễn phí.",
  },
  {
    slug: "ppa-tour-asia-2026-recap",
    publishedDate: "2026-06-11",
    updatedDate: "2026-06-11",
    author: "Cuong Nguyen",
    tags: ["ppa tour asia 2026", "ppa tour asia recap", "ly hoang nam pickleball", "truong vinh hien", "mb hanoi cup 2026", "ho chi minh city open 2026", "hong kong slam pickleball", "pickleball vietnam"],
    ctaPath: "/blog/ppa-tour-asia-2026-complete-guide",
    ctaLabel: { en: "Next: PPA Tour Asia 2026 — Full Schedule, Prize Money & Vietnam Stops", vi: "Tiếp theo: PPA Tour Asia 2026 — Lịch đầy đủ, tiền thưởng & các chặng Việt Nam" },
    heroImage: {
      src: "/images/blog/ppa-tour-asia-2026-recap-hero.webp",
      alt: "PPA Tour Asia 2026 mid-season recap infographic — a map of Asia marking the 10 tour stops with Hanoi, Kuala Lumpur and Macao completed, Vietnam's two stops (Hanoi and Ho Chi Minh City) flagged, two Vietnamese champions in red, and the road to the $1.1M Hong Kong Slam in October",
    },
    titleEn: "PPA Tour Asia 2026: Mid-Season Recap & Results So Far",
    titleVi: "PPA Tour Asia 2026: Tổng Kết Nửa Mùa & Kết Quả 3 Chặng",
    metaTitleEn: "PPA Tour Asia 2026 | Mid-Season Recap & Results",
    metaTitleVi: "PPA Tour Asia 2026 | Tổng Kết Nửa Mùa & Kết Quả",
    metaDescriptionEn: "PPA Tour Asia 2026 recap: 3 of 10 stops done — Ly Hoang Nam's historic Hanoi title, Vietnam's Hien Truong winning in KL, Tama's Macao double, and the road to the $1.1M Hong Kong Slam.",
    metaDescriptionVi: "Tổng kết PPA Tour Asia 2026: 3/10 chặng đã đá — Lý Hoàng Nam vô địch Hà Nội, Trương Vĩnh Hiển thắng ở Kuala Lumpur, Tama cú đúp ở Macao, và đường tới Hong Kong Slam $1.1 triệu.",
  },
  {
    slug: "mlp-vs-ppa-2026-which-tour-to-watch",
    publishedDate: "2026-06-09",
    updatedDate: "2026-06-09",
    author: "Cuong Nguyen",
    tags: ["mlp vs ppa", "mlp vs ppa 2026", "which pickleball tour to watch", "major league pickleball", "ppa tour", "united pickleball association", "ppa tour asia", "pickleball vietnam"],
    ctaPath: "/blog/ppa-tour-asia-2026-complete-guide",
    ctaLabel: { en: "Next: PPA Tour Asia 2026 — Full Schedule & Vietnam Stops", vi: "Tiếp theo: PPA Tour Asia 2026 — Lịch đầy đủ & các chặng tại Việt Nam" },
    heroImage: {
      src: "/images/blog/mlp-vs-ppa-2026-which-tour-to-watch-hero.webp",
      alt: "MLP vs PPA 2026 comparison graphic — the PPA Tour's individual knockout brackets versus Major League Pickleball's team-draft format, both under the United Pickleball Association (UPA), with PPA Tour Asia's Ho Chi Minh City Open in August highlighted for Vietnamese fans",
    },
    titleEn: "MLP vs PPA 2026: Which Pickleball Tour Should You Watch?",
    titleVi: "MLP vs PPA 2026: Nên Xem Giải Pickleball Nào?",
    metaTitleEn: "MLP vs PPA 2026 | Which Pickleball Tour to Watch",
    metaTitleVi: "MLP vs PPA 2026 | Nên Xem Giải Pickleball Nào",
    metaDescriptionEn: "MLP and PPA merged under the UPA in 2024 but keep different formats. A 2026 guide to which pro pickleball tour to watch — plus PPA Tour Asia's Vietnam stops.",
    metaDescriptionVi: "MLP và PPA đã sáp nhập dưới UPA từ 2024 nhưng giữ 2 thể thức riêng. Hướng dẫn 2026 chọn giải pickleball nên xem — kèm các chặng PPA Tour Asia tại Việt Nam.",
  },
  {
    slug: "vietnam-pickleball-federation-2026",
    publishedDate: "2026-06-08",
    updatedDate: "2026-06-08",
    author: "Cuong Nguyen",
    tags: ["vietnam pickleball federation", "lien doan pickleball viet nam", "vietnam pickleball governance", "pickleball national sports games 2026", "pickleball vietnam 2026", "da nang pickleball federation", "dupr vietnam"],
    ctaPath: "/blog/professional-pickleball-tours-guide-2026",
    ctaLabel: { en: "Next: Pro Pickleball Tours 2026 — PPA, MLP, APP & PPA Tour Asia Compared", vi: "Tiếp theo: Các giải Pickleball chuyên nghiệp 2026 — PPA, MLP, APP & PPA Tour Asia" },
    heroImage: {
      src: "/images/blog/vietnam-pickleball-federation-2026-hero.webp",
      alt: "Vietnam Pickleball Federation 2026 status and roadmap infographic — a map of Vietnam with emerging city-level pickleball federations in Hanoi, Da Nang and Ho Chi Minh City, and a timeline from the September 2025 organizing committee through the 2026 National Sports Games toward a still-pending national federation",
    },
    titleEn: "Is There a Vietnam Pickleball Federation? 2026 Status & Roadmap",
    titleVi: "Việt Nam Đã Có Liên Đoàn Pickleball Chưa? Hiện Trạng & Lộ Trình 2026",
    metaTitleEn: "Vietnam Pickleball Federation 2026 | Status & Roadmap",
    metaTitleVi: "Liên Đoàn Pickleball Việt Nam 2026 | Hiện Trạng & Lộ Trình",
    metaDescriptionEn: "No national pickleball federation exists in Vietnam yet (mid-2026) — only an organizing committee approved Sept 2025. The full status: roadmap, city-level federations, and what 2026 changes.",
    metaDescriptionVi: "Đến giữa 2026, Việt Nam chưa có liên đoàn pickleball quốc gia — mới có Ban vận động (9/2025). Tổng hợp hiện trạng: lộ trình, các liên đoàn cấp tỉnh/thành đã ra đời, và cột mốc 2026.",
  },
  {
    slug: "pickleball-erne-shot-tutorial",
    publishedDate: "2026-06-05",
    updatedDate: "2026-06-05",
    author: "Cuong Nguyen",
    tags: ["pickleball erne", "erne shot pickleball", "how to hit an erne in pickleball", "jump erne", "erne rules pickleball", "pickleball advanced shots", "pickleball volley", "kitchen rules pickleball"],
    ctaPath: "/blog/pickleball-doubles-stacking-strategy",
    ctaLabel: { en: "Next: Pickleball Stacking Strategy — Control Sides to Create Erne Chances", vi: "Tiếp theo: Chiến thuật Stacking — kiểm soát bên sân để tạo cơ hội erne" },
    heroImage: {
      src: "/images/blog/pickleball-erne-shot-tutorial-hero.webp",
      alt: "Dynamic side-angle action shot of a pickleball player leaping forward outside the kitchen line, mid-air, executing an erne volley right at the net while the opponent's dink floats toward the sideline."
    },
    titleEn: "The Erne in Pickleball: How to Hit It, Rules & Setup (2026)",
    titleVi: "Cú Erne Trong Pickleball: Cách Thực Hiện, Luật & Cách Giăng Bẫy (2026)",
    metaTitleEn: "Pickleball Erne Shot 2026 | How to Hit It & When",
    metaTitleVi: "Cú Erne Pickleball 2026 | Cách Thực Hiện & Khi Nào",
    metaDescriptionEn: "The pickleball erne explained: what it is, why it's legal, jump vs stationary erne, step-by-step technique, how to set it up, defense, mistakes, and drills.",
    metaDescriptionVi: "Cú erne pickleball là gì: vì sao hợp lệ, erne bật nhảy vs đứng sẵn, kỹ thuật từng bước, cách giăng bẫy, phòng thủ, lỗi phổ biến và bài tập.",
  },
  {
    slug: "pickleball-doubles-stacking-strategy",
    publishedDate: "2026-06-03",
    updatedDate: "2026-06-03",
    author: "Cuong Nguyen",
    tags: ["pickleball stacking", "pickleball stacking strategy", "stacking in pickleball explained", "pickleball stacking serve", "pickleball stacking return", "lefty righty pickleball", "pickleball doubles strategy", "pickleball positioning"],
    ctaPath: "/blog/pickleball-third-shot-drop-vs-drive",
    ctaLabel: { en: "Next: Third Shot Drop vs Drive — Win the Point After You Stack", vi: "Tiếp theo: Cú thứ 3 Drop vs Drive — thắng điểm sau khi stack" },
    heroImage: {
      src: "/images/blog/pickleball-doubles-stacking-strategy-hero.webp",
      alt: "Top-down diagram of a pickleball doubles court showing a stacking formation: two teammates positioned on the same side before the serve, with arrows indicating their rotation to preferred sides once the ball is in play, color-coded to show each partner's path."
    },
    titleEn: "Pickleball Stacking Strategy: A Complete Doubles Guide (2026)",
    titleVi: "Chiến Thuật Stacking Pickleball: Hướng Dẫn Đánh Đôi Đầy Đủ (2026)",
    metaTitleEn: "Pickleball Stacking Strategy 2026 | How & When to Stack",
    metaTitleVi: "Chiến Thuật Stacking Pickleball 2026 | Stack Thế Nào & Khi Nào",
    metaDescriptionEn: "Pickleball stacking explained: what it is, how to stack on the serve and return, the lefty-righty stack, hand signals, full vs half stack, mistakes, and drills.",
    metaDescriptionVi: "Stacking pickleball là gì: cách stack khi giao và khi trả bóng, stack thuận-nghịch tay, tín hiệu tay, full stack vs half stack, lỗi phổ biến và bài tập.",
  },
  {
    slug: "pickleball-third-shot-drop-vs-drive",
    publishedDate: "2026-06-01",
    updatedDate: "2026-06-01",
    author: "Cuong Nguyen",
    tags: ["third shot drop pickleball", "third shot drive vs drop", "pickleball third shot", "third shot drop technique", "pickleball drive", "pickleball drop shot", "pickleball doubles strategy", "get to the kitchen"],
    ctaPath: "/blog/pickleball-dink-technique-mastery",
    ctaLabel: { en: "Next: Pickleball Dink Technique — Master the Soft Game", vi: "Tiếp theo: Kỹ thuật Dink Pickleball — làm chủ soft game" },
    heroImage: {
      src: "/images/blog/pickleball-third-shot-drop-vs-drive-hero.webp",
      alt: "Side-by-side comparison of a pickleball player executing a third shot drop with a soft high arc landing in the kitchen versus the same player hitting a flat, fast third shot drive, illustrating the two third-shot options for the 2026 strategy guide."
    },
    titleEn: "Third Shot Drop vs Drive in Pickleball: Which to Hit & When (2026)",
    titleVi: "Cú Thứ 3 Pickleball: Drop vs Drive — Đánh Cú Nào & Khi Nào (2026)",
    metaTitleEn: "Third Shot Drop vs Drive Pickleball 2026 | Which & When",
    metaTitleVi: "Cú Thứ 3 Pickleball: Drop vs Drive 2026 | Cú Nào & Khi Nào",
    metaDescriptionEn: "Third shot drop vs drive in pickleball: what each shot does, the mechanics, when to drop, when to drive, the hybrid drive-and-drop, common mistakes, and drills.",
    metaDescriptionVi: "Cú thứ 3 pickleball drop vs drive: mỗi cú làm gì, cơ học, khi nào drop, khi nào drive, combo drive-and-drop, lỗi phổ biến và bài tập.",
  },
  {
    slug: "pickleball-dink-technique-mastery",
    publishedDate: "2026-06-01",
    updatedDate: "2026-06-01",
    author: "Cuong Nguyen",
    tags: ["how to dink pickleball", "pickleball dink technique", "pickleball dink", "cross court dink", "topspin dink", "pickleball kitchen game", "pickleball soft game", "dink drills"],
    ctaPath: "/blog/pickleball-doubles-strategy-guide",
    ctaLabel: { en: "Next: Pickleball Doubles Strategy — Positioning & Shot Selection", vi: "Tiếp theo: Chiến thuật Pickleball đôi — vị trí & chọn cú đánh" },
    heroImage: {
      src: "/images/blog/pickleball-dink-technique-mastery-hero.webp",
      alt: "Close-up action shot of a pickleball player at the kitchen line executing a soft dink shot with an open paddle face, the ball captured mid-air just clearing the net, a blurred opponent in the background, illustrating proper dink technique for the 2026 mastery guide."
    },
    titleEn: "How to Dink in Pickleball: Technique Mastery Guide 2026",
    titleVi: "Kỹ Thuật Dink Pickleball: Hướng Dẫn Cơ Bản Đến Nâng Cao 2026",
    metaTitleEn: "How to Dink in Pickleball: Technique Mastery Guide 2026",
    metaTitleVi: "Kỹ Thuật Dink Pickleball 2026 | Cơ Bản Đến Nâng Cao",
    metaDescriptionEn: "Master the pickleball dink: grip, paddle face, contact point, cross-court vs straight, topspin dink, the 5 most common mistakes, and 4 drills to practice.",
    metaDescriptionVi: "Làm chủ cú dink pickleball: cầm vợt, mặt vợt, điểm chạm, dink chéo sân vs thẳng, dink topspin, 5 lỗi phổ biến và 4 bài tập luyện.",
  },
  {
    slug: "dupr-thepicklehub-user-guide",
    publishedDate: "2026-05-29",
    updatedDate: "2026-05-29",
    author: "Cuong Nguyen",
    tags: ["dupr thepicklehub", "dupr integration", "dupr vietnam", "pickleball rating vietnam", "dupr connect", "log pickleball match", "dupr leaderboard vietnam", "pickleball thepicklehub"],
    ctaPath: "/dupr",
    ctaLabel: { en: "Connect Your DUPR Account Now", vi: "Kết Nối Tài Khoản DUPR Ngay" },
    heroImage: {
      src: "/images/blog/dupr-thepicklehub-user-guide-hero.webp",
      alt: "A 16:9 editorial product hero showing the ThePickleHub.net dashboard on a laptop, featuring a green Connect DUPR header button, a DUPR rating pill displaying singles 4.27 and doubles 4.41, and a 30-day rating history line chart in the background, with subtle pickleball paddle and ball props and a faint Vietnam map outline, illustrating the 2026 DUPR integration user guide for ThePickleHub."
    },
    titleEn: "DUPR on ThePickleHub: Complete User Guide 2026 — Connect, Log Matches, Rankings",
    titleVi: "Hướng Dẫn Dùng DUPR Trên ThePickleHub 2026 | Connect, Log Trận, Bảng Xếp Hạng",
    metaTitleEn: "DUPR on ThePickleHub Guide 2026 | Connect + Log Matches",
    metaTitleVi: "Dùng DUPR Trên ThePickleHub 2026 | Connect + Log Trận",
    metaDescriptionEn: "Connect DUPR to ThePickleHub in one click, log matches with opponent confirmation, submit to DUPR, and track your rating on the Vietnam DUPR leaderboard.",
    metaDescriptionVi: "Kết nối DUPR với ThePickleHub trong 1-click, log trận đấu có đối thủ xác nhận, admin submit lên DUPR — và theo dõi rating trên bảng xếp hạng DUPR Việt Nam.",
  },
  {
    slug: "pickleball-court-dimensions-setup-guide",
    publishedDate: "2026-05-29",
    updatedDate: "2026-05-29",
    author: "Cuong Nguyen",
    tags: ["pickleball court dimensions", "pickleball court size", "pickleball kitchen size", "pickleball net height", "convert tennis court to pickleball", "mark a pickleball court", "pickleball court vietnam", "pickleball setup"],
    ctaPath: "/blog/how-to-play-pickleball",
    ctaLabel: { en: "Next: How to Play Pickleball — 7-Day Beginner Plan", vi: "Tiếp theo: Hướng dẫn chơi Pickleball — lộ trình 7 ngày cho người mới" },
    heroImage: {
      src: "/images/blog/pickleball-court-dimensions-setup-guide-hero.webp",
      alt: "Top-down diagrammatic illustration of a regulation pickleball court with measurements labeled in both feet and meters — 44 feet by 20 feet playing area, 7-foot non-volley kitchen on each side of the net, 22-foot service area depth, and 36-inch net height — color-coded zones on a clean technical-drawing background for the 2026 court dimensions and setup guide."
    },
    titleEn: "Pickleball Court Dimensions & Setup Guide 2026 | Sizes + Diagram",
    titleVi: "Kích Thước Sân Pickleball Tiêu Chuẩn 2026 | Sơ Đồ + Cách Vẽ Sân",
    metaTitleEn: "Pickleball Court Dimensions & Setup Guide 2026 | Sizes + Diagram",
    metaTitleVi: "Kích Thước Sân Pickleball Tiêu Chuẩn 2026 | Sơ Đồ + Cách Vẽ Sân",
    metaDescriptionEn: "Official pickleball court dimensions: 44×20 ft playing area, 7 ft kitchen, net height, total space needed. Plus how to mark a court and convert a tennis court.",
    metaDescriptionVi: "Kích thước sân pickleball chuẩn: sân đấu 13,41×6,1 m, khu bếp 2,13 m, chiều cao lưới, diện tích tổng cần thiết. Kèm cách kẻ sân và tận dụng sân tennis.",
  },
  {
    slug: "vietnam-dupr-leaderboard-launch",
    publishedDate: "2026-05-27",
    updatedDate: "2026-05-27",
    author: "Cuong Nguyen",
    tags: ["dupr", "dupr vietnam", "vietnam pickleball ranking", "dupr leaderboard", "thepicklehub", "pickleball vietnam", "asia pickleball", "tournament rating"],
    ctaPath: "/rankings",
    ctaLabel: { en: "View the Vietnam DUPR Leaderboard", vi: "Xem bảng xếp hạng DUPR Việt Nam" },
    heroImage: {
      src: "/images/blog/vietnam-dupr-leaderboard-launch-hero.webp",
      alt: "Vietnam DUPR pickleball leaderboard on ThePickleHub.net showing top Vietnamese players with live DUPR doubles and singles ratings, ranked highest to lowest in a dark editorial table layout."
    },
    titleEn: "Vietnam DUPR Leaderboard Launches on ThePickleHub | Live Rankings, Bracket Seeding, Balanced Matchmaking",
    titleVi: "Bảng xếp hạng DUPR Việt Nam ra mắt trên ThePickleHub | Cập nhật real-time, seed bracket tự động, ghép cặp cân bằng",
    metaTitleEn: "Vietnam DUPR Leaderboard | Live Pickleball Rankings on ThePickleHub",
    metaTitleVi: "Bảng xếp hạng DUPR Việt Nam | Cập nhật real-time trên ThePickleHub",
    metaDescriptionEn: "ThePickleHub now hosts a live Vietnam DUPR pickleball leaderboard updated by webhook. Plus DUPR-required tournaments, auto-seeded brackets, and balanced Mexicano pairings.",
    metaDescriptionVi: "ThePickleHub ra mắt bảng xếp hạng DUPR Việt Nam cập nhật real-time qua webhook. Kèm tính năng giải đấu yêu cầu DUPR, seed bracket tự động, ghép cặp Mexicano cân bằng.",
  },
  {
    slug: "pickleball-vs-padel-vs-paddle-tennis",
    publishedDate: "2026-05-26",
    updatedDate: "2026-05-26",
    author: "Cuong Nguyen",
    tags: ["pickleball vs padel", "pickleball vs paddle tennis", "padel vs pickleball", "racquet sports comparison", "padel vietnam", "paddle tennis explained", "pickleball court dimensions", "pickleball beginners"],
    ctaPath: "/blog/pickleball-for-tennis-players-2026",
    ctaLabel: { en: "Next: Pickleball for Tennis Players 2026 — 5 Habits to Unlearn", vi: "Tiếp theo: Pickleball cho người chơi tennis 2026 — 5 thói quen cần bỏ" },
    heroImage: {
      src: "/images/blog/pickleball-vs-padel-vs-paddle-tennis-hero.webp",
      alt: "Three top-down court diagrams side by side at the same visual scale, showing pickleball court (44 by 20 feet, kitchen marked), padel court (20 by 10 meters with glass walls in light blue), and paddle tennis POP court (50 by 20 feet, no walls), each labeled with sport name and dimensions in a clean illustrative diagram style on a white background for the 2026 racquet sports comparison guide"
    },
    titleEn: "Pickleball vs Padel vs Paddle Tennis: Complete Guide 2026",
    titleVi: "Pickleball vs Padel vs Paddle Tennis: So Sánh Đầy Đủ 2026",
    metaTitleEn: "Pickleball vs Padel vs Paddle Tennis: Complete Guide 2026",
    metaTitleVi: "Pickleball vs Padel vs Paddle Tennis: So Sánh 2026",
    metaDescriptionEn: "Pickleball vs padel vs paddle tennis: full 2026 comparison of court size, rules, scoring, equipment, where each sport is popular, what to try first.",
    metaDescriptionVi: "Pickleball, padel hay paddle tennis khác nhau thế nào? So sánh 2026 đầy đủ: sân, luật, dụng cụ, nơi phổ biến tại VN/Á — và môn nào nên thử trước.",
  },
  {
    slug: "best-pickleball-paddles-beginners-2026",
    publishedDate: "2026-05-24",
    updatedDate: "2026-05-24",
    author: "Cuong Nguyen",
    tags: ["best pickleball paddles", "beginner paddle", "paddle buying guide", "pickleball equipment", "joola", "selkirk", "gamma", "pickleball vietnam", "asia"],
    ctaPath: "/blog/how-to-play-pickleball",
    ctaLabel: { en: "Next: How to Play Pickleball — Complete Beginner Guide", vi: "Tiếp theo: Hướng dẫn chơi Pickleball cho người mới" },
    heroImage: {
      src: "/images/blog/best-pickleball-paddles-beginners-2026-hero.webp",
      alt: "Top-down product photo of seven beginner pickleball paddles arranged in a fan layout on a neutral wood background, showing paddle face colors ranging from white to black with varied grip wraps, sports equipment catalog style for the 2026 best pickleball paddles for beginners buyer guide"
    },
    titleEn: "Best Pickleball Paddles for Beginners 2026: 7 Top Picks (Asia Buyer's Guide)",
    titleVi: "Vợt Pickleball Tốt Nhất Cho Người Mới 2026: 7 Lựa Chọn (Hướng Dẫn Mua Tại VN)",
    metaTitleEn: "Best Pickleball Paddles for Beginners 2026 | 7 Top Picks",
    metaTitleVi: "Vợt Pickleball Tốt Nhất Cho Người Mới 2026 (7 Lựa Chọn)",
    metaDescriptionEn: "Picking your first pickleball paddle without overspending. 7 beginner-friendly paddles for 2026 with weight, face, grip specs — plus what to avoid in VN.",
    metaDescriptionVi: "Chọn vợt pickleball đầu tiên không bị \"cháy túi\". 7 mẫu vợt cho người mới 2026 — phân tích trọng lượng, mặt vợt, cán + lỗi cần tránh khi mua tại VN.",
  },
  {
    slug: "pickleball-for-tennis-players-2026",
    publishedDate: "2026-05-22",
    updatedDate: "2026-05-22",
    author: "Cuong Nguyen",
    tags: ["pickleball for tennis players", "tennis to pickleball", "tennis vs pickleball", "beginner", "technique", "transition guide", "unlearn", "vietnam pickleball"],
    ctaPath: "/blog/how-to-play-pickleball",
    ctaLabel: { en: "Read: How to Play Pickleball — Complete Beginner Guide", vi: "Đọc tiếp: Hướng dẫn chơi Pickleball cho người mới bắt đầu" },
    heroImage: {
      src: "/images/blog/pickleball-for-tennis-players-2026-hero.webp",
      alt: "Split-screen sports photo: left side a tennis player executing a deep baseline forehand on a clay court, right side the same player at the kitchen line on a pickleball court holding a paddle in a compact ready position, illustrating the transition from tennis to pickleball and the 5 habits tennis players need to unlearn"
    },
    titleEn: "Pickleball for Tennis Players: 5 Things to Unlearn (2026 Guide)",
    titleVi: "Từ tennis chuyển sang pickleball: 5 thói quen cần \"quên\" (2026)",
    metaTitleEn: "Pickleball for Tennis Players 2026 | 5 Habits to Unlearn",
    metaTitleVi: "Tennis sang Pickleball 2026 | 5 thói quen phải sửa",
    metaDescriptionEn: "Tennis players struggle with pickleball not because it's harder — they bring 5 ingrained habits that backfire. Here's what to unlearn and the 7-day fix.",
    metaDescriptionVi: "Người chơi tennis chuyển sang pickleball không thua vì kỹ thuật yếu — họ mang theo 5 thói quen phản tác dụng. Đây là cách sửa và lịch tập 7 ngày.",
  },
  {
    slug: "dupr-rating-improvement-30-day-plan",
    publishedDate: "2026-05-20",
    updatedDate: "2026-05-20",
    author: "Cuong Nguyen",
    tags: ["dupr", "dupr rating", "pickleball rating", "training plan", "improvement", "30 day plan", "dupr algorithm", "performance vs expectation", "vietnam pickleball"],
    ctaPath: "/blog/dupr-algorithm-explained-performance-vs-expectation",
    ctaLabel: { en: "Read Part 2: How the DUPR Algorithm Actually Works", vi: "Đọc Phần 2: Thuật toán DUPR — thắng mất điểm, thua tăng điểm" },
    heroImage: {
      src: "/images/blog/dupr-rating-improvement-30-day-plan-hero.webp",
      alt: "A vertical bar chart showing a DUPR (Dynamic Universal Pickleball Rating) climbing from 3.50 to 4.20 across 30 days, beside a pickleball paddle and DUPR logo, illustrating a realistic week-by-week training plan to improve a pickleball rating."
    },
    titleEn: "How to Improve Your DUPR Rating: A Realistic 30-Day Plan",
    titleVi: "Tăng điểm DUPR trong 30 ngày: kế hoạch thực tế (không hứa nhanh)",
    metaTitleEn: "Improve DUPR Rating in 30 Days | Realistic Training Plan 2026",
    metaTitleVi: "Tăng DUPR 30 ngày | Kế hoạch luyện tập thực tế 2026",
    metaDescriptionEn: "A 30-day plan to raise your DUPR rating: how DUPR's algorithm rewards consistent play, the 4 rules from Part 2, and a week-by-week training schedule.",
    metaDescriptionVi: "Kế hoạch 30 ngày tăng điểm DUPR thực tế: hiểu thuật toán DUPR, 4 quy tắc từ Phần 2, lịch luyện tập theo tuần, 3 sai lầm cần tránh.",
  },
  {
    slug: "professional-pickleball-tours-guide-2026",
    publishedDate: "2026-05-18",
    updatedDate: "2026-05-18",
    author: "Cuong Nguyen",
    tags: ["professional pickleball", "ppa tour", "mlp", "ppa tour asia", "app tour", "upa", "2026", "pro pickleball comparison", "asia"],
    ctaPath: "/blog/ppa-tour-asia-2026-complete-guide",
    ctaLabel: { en: "Read: PPA Tour Asia 2026 Complete Guide", vi: "Đọc: Hướng dẫn đầy đủ PPA Tour Asia 2026" },
    heroImage: {
      src: "/images/blog/professional-pickleball-tours-guide-2026-hero.webp",
      alt: "Professional pickleball tours 2026 — PPA Tour, MLP, PPA Tour Asia, and APP Tour shown across global venues with crowded stadiums and broadcast cameras, the four pro circuits operating under the UPA umbrella that define competitive pickleball in 2026"
    },
    titleEn: "Professional Pickleball Tours 2026: Complete Guide to PPA, MLP, PPA Tour Asia, and APP",
    titleVi: "Các giải Pickleball chuyên nghiệp 2026: Hướng dẫn đầy đủ về PPA, MLP, PPA Tour Asia và APP",
    metaTitleEn: "Pro Pickleball Tours 2026 | PPA vs MLP vs APP vs PPA Asia Compared",
    metaTitleVi: "Pro Pickleball 2026 | PPA, MLP, APP, PPA Tour Asia — So sánh đầy đủ",
    metaDescriptionEn: "2026 guide to pro pickleball tours: PPA Tour, MLP, PPA Tour Asia, APP — schedules, prize money, formats, top players, how to watch from Asia.",
    metaDescriptionVi: "Hướng dẫn đầy đủ về 4 giải pickleball chuyên nghiệp 2026 — PPA Tour, MLP, PPA Tour Asia, APP — lịch thi đấu, tiền thưởng, format, top VĐV và cách xem từ Việt Nam.",
  },  {
    slug: "pickleball-tour-wars-2023-explained",
    publishedDate: "2026-05-05",
    updatedDate: "2026-05-05",
    author: "Cuong Nguyen",
    tags: ["tour wars", "ppa tour", "mlp", "upa", "professional pickleball", "history", "gold contract", "asia"],
    ctaPath: "/blog/app-tour-vs-ppa-tour-contracts-2026",
    ctaLabel: { en: "Read: APP Tour vs PPA Tour Contracts in 2026", vi: "Đọc tiếp: Hợp đồng APP Tour vs PPA Tour 2026" },
    heroImage: {
      src: "/images/blog/pickleball-tour-wars-2023-hero.webp",
      alt: "Pickleball Tour Wars 2023 — the 10-day signing frenzy in August 2023 between PPA Tour and Major League Pickleball that reshaped professional pickleball, created exclusive Gold Contracts, and set the stage for the 2024 UPA merger"
    },
    titleEn: "Pickleball Tour Wars 2023: The 10 Days That Reshaped Pro Pickleball Forever",
    titleVi: "Tour Wars 2023: 10 ngày thay đổi pickleball chuyên nghiệp mãi mãi",
    metaTitleEn: "Pickleball Tour Wars 2023 Explained | 10 Days That Changed Pro Pickleball",
    metaTitleVi: "Tour Wars 2023 | 10 ngày định hình pickleball pro hiện đại",
    metaDescriptionEn: "Pickleball Tour Wars 2023: how PPA and MLP fought for 10 days, why Gold Contracts only exist from that window, and what it means for Vietnamese pros today.",
    metaDescriptionVi: "Tour Wars 2023: PPA và MLP đua ký 150 VĐV trong 10 ngày, tạo Gold Contract mãi mãi, dẫn đến sáp nhập UPA — và ý nghĩa cho VĐV Việt Nam hôm nay.",
  },  {
    slug: "app-tour-vs-ppa-tour-contracts-2026",
    publishedDate: "2026-05-05",
    updatedDate: "2026-05-05",
    author: "Cuong Nguyen",
    tags: ["app tour", "ppa tour", "professional pickleball", "contracts", "quang duong", "asia", "global pickleball alliance"],
    ctaPath: "/blog/ppa-tour-asia-2026-complete-guide",
    ctaLabel: { en: "Read the PPA Tour Asia 2026 Guide", vi: "Đọc hướng dẫn PPA Tour Asia 2026" },
    heroImage: {
      src: "/images/blog/app-tour-vs-ppa-tour-contracts-hero.webp",
      alt: "APP Tour vs PPA Tour 2026 contract comparison — APP's open free-agent model versus PPA's exclusive multi-year deals, with Quang Duong's APP signing as a case study from Vietnam"
    },
    titleEn: "APP Tour vs PPA Tour: How Pickleball's Two Pro Contracts Actually Work in 2026",
    titleVi: "Hợp đồng APP Tour vs PPA Tour: Hai cách tổ chức pro pickleball năm 2026",
    metaTitleEn: "APP Tour vs PPA Tour 2026 | Contracts, Money & Exclusivity Compared",
    metaTitleVi: "APP Tour vs PPA Tour 2026 | Hợp đồng, tiền thưởng, độc quyền",
    metaDescriptionEn: "APP Tour vs PPA Tour 2026: contract structures, prize money, exclusivity, the Global Pickleball Alliance, and Quang Duong's APP deal explained.",
    metaDescriptionVi: "So sánh APP Tour vs PPA Tour 2026: hợp đồng, tiền thưởng, điều khoản độc quyền, Global Pickleball Alliance, và hợp đồng APP của Quang Dương.",
  },  {
    slug: "how-to-play-pickleball",
    publishedDate: "2026-04-26",
    updatedDate: "2026-04-26",
    author: "Cuong Nguyen",
    tags: ["how to play pickleball", "beginner", "pickleball technique", "dink", "third shot drop", "asia"],
    ctaPath: "/tools/quick-tables",
    ctaLabel: { en: "Run Your First Game", vi: "Chấm điểm trận đầu tiên" },
    heroImage: {
      src: "/images/blog/how-to-play-pickleball-hero.webp",
      alt: "How to play pickleball — beginner-friendly 7-day plan covering gear, grip, six core shots, and doubles strategy, taught to 200+ Vietnamese players in Hanoi and Ho Chi Minh City"
    },
    titleEn: "How to Play Pickleball: 7-Day Beginner Plan (Tested with 200+ Players in Vietnam)",
    titleVi: "Cách chơi Pickleball cho người mới: Lộ trình 7 ngày từ 0 đến đánh được",
    metaTitleEn: "How to Play Pickleball | 7-Day Beginner Plan Tested in Vietnam",
    metaTitleVi: "Cách chơi Pickleball cho người mới | Lộ trình 7 ngày từ 0",
    metaDescriptionEn: "How to play pickleball: beginner gear, grip, 6 core shots, and a 7-day practice plan tested with 200+ Vietnamese players. Start playing in week one.",
    metaDescriptionVi: "Hướng dẫn cách chơi Pickleball cho người mới từ A đến Z: dụng cụ cần mua, kỹ thuật cơ bản, lộ trình 7 ngày tập luyện, lỗi thường gặp. Bắt đầu chơi tự tin sau 1 tuần.",
  },  {
    slug: "tournament-organizer-hub",
    publishedDate: "2026-04-25",
    updatedDate: "2026-04-25",
    author: "The PickleHub Team",
    tags: ["organize", "tournament", "hub", "guide", "directory"],
    ctaPath: "/tools",
    ctaLabel: { en: "Open Free Tournament Tools", vi: "Mở công cụ tổ chức miễn phí" },
    heroImage: {
      src: "/images/blog/tournament-organizer-hub-hero.webp",
      alt: "Pickleball tournament organizer hub — workflow from format selection through bracket generation, scoring, livestream, and software comparison"
    },
    titleEn: "Pickleball Tournament Organizer Hub — Every Guide, Tool & Format in One Place",
    titleVi: "Hub Tổ chức giải Pickleball — Mọi hướng dẫn, công cụ và thể thức trong một trang",
    metaTitleEn: "Pickleball Tournament Organizer Hub | Formats, Brackets, Tools 2026",
    metaTitleVi: "Hub Tổ chức giải Pickleball | Thể thức, Bracket, Công cụ 2026",
    metaDescriptionEn: "Pickleball tournament organizer hub 2026: choose a format, build brackets, manage scoring, livestream, and compare free software — all from one page.",
    metaDescriptionVi: "Hub đầy đủ cho ban tổ chức giải pickleball 2026. Chọn thể thức, tạo bracket, quản lý điểm, livestream và so sánh phần mềm miễn phí — tất cả liên kết trong một trang.",
  },  {
    slug: "pickleball-world-cup-2026-da-nang",
    publishedDate: "2026-04-23",
    updatedDate: "2026-04-23",
    author: "The PickleHub Team",
    tags: ["world cup pickleball", "da nang", "vietnam", "tournament", "asia", "2026", "guide"],
    ctaPath: "/tournaments",
    ctaLabel: { en: "Browse Tournaments", vi: "Xem các giải đấu" },
    heroImage: {
      src: "/images/blog/pickleball-world-cup-2026-da-nang-hero.webp",
      alt: "Pickleball World Cup 2026 in Da Nang, Vietnam — Aug 30 to Sep 6, 2026, Tien Son Sports Palace, ~80 countries and 4,000 athletes"
    },
    titleEn: "Pickleball World Cup 2026 in Da Nang, Vietnam — Complete Guide",
    titleVi: "World Cup Pickleball 2026 tại Đà Nẵng — Hướng dẫn đầy đủ",
    metaTitleEn: "Pickleball World Cup 2026 Da Nang | Dates, Teams, Venues, How to Watch",
    metaTitleVi: "World Cup Pickleball 2026 Đà Nẵng | Lịch thi đấu, Đội tuyển, Cách xem",
    metaDescriptionEn: "Pickleball World Cup 2026 in Da Nang, Vietnam (Aug 30–Sep 6). Up to 80 nations, 4,000 athletes. Dates, venues, format, Vietnam team.",
    metaDescriptionVi: "Đà Nẵng đăng cai World Cup Pickleball 2026 từ 30/8 – 6/9. Gần 80 quốc gia, 4.000 VĐV. Lịch thi đấu, địa điểm, đội tuyển Việt Nam — thông tin đầy đủ.",
  },  {
    slug: "best-pickleball-tournament-software-2026",
    publishedDate: "2025-12-15",
    updatedDate: "2026-03-27",
    author: "The PickleHub Team",
    tags: ["tournament", "software", "comparison"],
    ctaPath: "/tools",
    ctaLabel: { en: "Try Free Tournament Tools", vi: "Dùng thử miễn phí" },
    heroImage: undefined,
    titleEn: "Best Pickleball Tournament Software in 2026 — Free Tools Compared",
    titleVi: "Phần mềm tổ chức giải Pickleball tốt nhất 2026 — So sánh công cụ miễn phí",
    metaTitleEn: "Best Pickleball Tournament Software 2026 | Free Bracket Tools Compared",
    metaTitleVi: "Phần mềm tổ chức giải Pickleball tốt nhất 2026 | So sánh công cụ tạo bracket miễn phí",
    metaDescriptionEn: "Compare the best pickleball tournament software in 2026: free bracket generators, round robin tools, MLP team match platforms. No signup.",
    metaDescriptionVi: "So sánh phần mềm tổ chức giải pickleball tốt nhất 2026. Tạo bracket miễn phí, round robin, MLP team match cho ban tổ chức. Không cần đăng ký.",
  },  {
    slug: "free-pickleball-bracket-generator",
    publishedDate: "2026-03-29",
    updatedDate: "2026-03-29",
    author: "The PickleHub Team",
    tags: ["bracket", "generator", "free", "tool"],
    ctaPath: "/tools/quick-tables",
    ctaLabel: { en: "Create Free Bracket Now", vi: "Tạo bracket miễn phí ngay" },
    heroImage: undefined,
    titleEn: "Free Pickleball Bracket Generator — Create Tournament Brackets in 60 Seconds",
    titleVi: "Tạo Bracket Pickleball miễn phí — Bracket giải đấu trong 60 giây",
    metaTitleEn: "Free Pickleball Bracket Generator 2026 | Create Brackets in 60 Seconds",
    metaTitleVi: "Tạo Bracket Pickleball miễn phí 2026 | Tạo bracket trong 60 giây",
    metaDescriptionEn: "Free pickleball bracket generator: round robin, single + double elimination, with real-time scoring. Build a tournament bracket in 60 seconds.",
    metaDescriptionVi: "Tạo bracket giải pickleball miễn phí tức thì. Vòng tròn, loại trực tiếp, loại kép với chấm điểm realtime. Không cần đăng ký.",
  },  {
    slug: "how-to-create-pickleball-bracket",
    publishedDate: "2025-11-20",
    updatedDate: "2026-03-27",
    author: "The PickleHub Team",
    tags: ["bracket", "guide", "round-robin"],
    ctaPath: "/tools/quick-tables",
    ctaLabel: { en: "Create Your Bracket Now", vi: "Tạo bracket ngay" },
    heroImage: undefined,
    titleEn: "How to Create a Pickleball Bracket — Step-by-Step Guide",
    titleVi: "Cách tạo Bracket giải Pickleball — Hướng dẫn từng bước",
    metaTitleEn: "How to Create a Pickleball Bracket | Free Step-by-Step Guide 2026",
    metaTitleVi: "Cách tạo Bracket giải Pickleball | Hướng dẫn miễn phí 2026",
    metaDescriptionEn: "How to create a pickleball bracket for round robin, single elimination, and double elimination — with a free bracket generator + live scoring.",
    metaDescriptionVi: "Hướng dẫn tạo bracket giải pickleball cho vòng tròn, loại trực tiếp, và loại kép. Công cụ tạo bracket miễn phí với chấm điểm realtime.",
  },  {
    slug: "how-to-organize-pickleball-tournament",
    publishedDate: "2026-03-20",
    updatedDate: "2026-03-29",
    author: "The PickleHub Team",
    tags: ["organize", "tournament", "guide"],
    ctaPath: "/tools",
    ctaLabel: { en: "Start Organizing Now", vi: "Bắt đầu tổ chức ngay" },
    heroImage: undefined,
    titleEn: "How to Organize a Pickleball Tournament — The Complete Organizer's Checklist",
    titleVi: "Cách tổ chức giải đấu Pickleball — Checklist đầy đủ cho ban tổ chức",
    metaTitleEn: "How to Organize a Pickleball Tournament | Complete Checklist 2026",
    metaTitleVi: "Cách tổ chức giải Pickleball | Checklist đầy đủ 2026",
    metaDescriptionEn: "Step-by-step guide to organize a pickleball tournament: venue, format, registration, scheduling, scoring, and free tools to run the event.",
    metaDescriptionVi: "Hướng dẫn từng bước tổ chức giải pickleball. Địa điểm, thể thức, đăng ký, lịch thi đấu, chấm điểm, và công cụ miễn phí. Mọi thứ bạn cần để chạy giải thành công.",
  },  {
    slug: "how-to-watch-ppa-tour-live-2026",
    publishedDate: "2026-04-16",
    updatedDate: "2026-04-16",
    author: "The PickleHub Team",
    tags: ["ppa tour", "live streaming", "watch live", "pickleball tv", "2026"],
    ctaPath: "/live",
    ctaLabel: { en: "Watch Free Tournaments", vi: "Xem giải đấu miễn phí" },
    heroImage: { src: "/images/blog/how-to-watch-ppa-tour-live-2026-hero.webp?v=2", alt: "PPA Tour professional pickleball match being broadcast live with multiple camera angles and streaming overlay" },
    titleEn: "How to Watch PPA Tour Live in 2026 — Every Streaming Platform & Free Options",
    titleVi: "Cách Xem PPA Tour Trực Tiếp Năm 2026 — Tất Cả Nền Tảng & Tùy Chọn Miễn Phí",
    metaTitleEn: "How to Watch PPA Tour Live 2026 | Streaming Platforms, Schedules & Free Options",
    metaTitleVi: "Xem PPA Tour Trực Tiếp 2026 | Nền Tảng, Lịch Trình & Tùy Chọn Miễn Phí",
    metaDescriptionEn: "Watch PPA Tour live in 2026 on PBTV, Amazon Prime, CBS, ESPN, and Fox Sports. Plus free YouTube highlights + ThePickleHub livestreams.",
    metaDescriptionVi: "Xem PPA Tour trực tiếp năm 2026 trên PBTV, Amazon Prime, CBS Sports, ESPN và Fox Sports. Bao gồm highlights YouTube miễn phí và livestream miễn phí từ ThePickleHub.",
  },  {
    slug: "mlp-format-explained",
    publishedDate: "2026-03-29",
    updatedDate: "2026-03-29",
    author: "The PickleHub Team",
    tags: ["mlp", "team-match", "format", "rules"],
    ctaPath: "/tools/team-match",
    ctaLabel: { en: "Create MLP Team Match", vi: "Tạo giải đồng đội MLP" },
    heroImage: undefined,
    titleEn: "MLP Format Explained — Major League Pickleball Team Match Rules & How to Play",
    titleVi: "Thể thức MLP giải thích — Luật thi đấu đồng đội Major League Pickleball",
    metaTitleEn: "MLP Format Explained 2026 | Major League Pickleball Rules & Team Match Guide",
    metaTitleVi: "Thể thức MLP Pickleball 2026 | Luật đồng đội Major League Pickleball",
    metaDescriptionEn: "MLP format explained: Major League Pickleball team match rules, dreambreaker, lineup strategy, and how to organize your own MLP-style event.",
    metaDescriptionVi: "Tìm hiểu thể thức MLP trong pickleball. Hướng dẫn đầy đủ về luật thi đấu đồng đội Major League Pickleball, dreambreaker, chiến thuật lineup.",
  },  {
    slug: "pickleball-bracket-templates",
    publishedDate: "2026-03-29",
    updatedDate: "2026-03-29",
    author: "The PickleHub Team",
    tags: ["bracket", "template", "tournament"],
    ctaPath: "/tools/quick-tables",
    ctaLabel: { en: "Use Free Bracket Template", vi: "Dùng mẫu bracket miễn phí" },
    heroImage: undefined,
    titleEn: "Pickleball Bracket Templates — Free Templates for Every Tournament Format",
    titleVi: "Mẫu Bracket Pickleball — Mẫu miễn phí cho mọi thể thức giải đấu",
    metaTitleEn: "Pickleball Bracket Templates 2026 | Free Download for 4-64 Players",
    metaTitleVi: "Mẫu Bracket Pickleball 2026 | Miễn phí cho 4-64 người chơi",
    metaDescriptionEn: "Free pickleball bracket templates for round robin, single + double elimination. Sizes for 4, 8, 16, 32, 64 players with live scoring.",
    metaDescriptionVi: "Mẫu bracket pickleball miễn phí cho vòng tròn, loại trực tiếp, và loại kép. Mẫu cho 4, 8, 16, 32, và 64 người chơi với chấm điểm realtime.",
  },  {
    slug: "pickleball-doubles-strategy-guide",
    publishedDate: "2026-03-22",
    updatedDate: "2026-03-29",
    author: "The PickleHub Team",
    tags: ["doubles", "strategy", "tips"],
    ctaPath: "/tools/doubles-elimination",
    ctaLabel: { en: "Create Doubles Bracket", vi: "Tạo bracket đôi" },
    heroImage: undefined,
    titleEn: "Pickleball Doubles Strategy — Winning Tips for Tournament Players",
    titleVi: "Chiến thuật Pickleball đôi — Mẹo thắng cho người chơi giải đấu",
    metaTitleEn: "Pickleball Doubles Strategy & Tips | Tournament Winning Guide 2026",
    metaTitleVi: "Chiến thuật Pickleball đôi | Mẹo thắng giải 2026",
    metaDescriptionEn: "Pickleball doubles strategy for tournaments: partner communication, court positioning, stacking, and when to attack the kitchen line.",
    metaDescriptionVi: "Nắm vững chiến thuật pickleball đôi cho giải đấu. Giao tiếp đồng đội, vị trí sân, stacking, và khi nào tấn công kitchen. Cải thiện game đôi ngay hôm nay.",
  },  {
    slug: "pickleball-live-streaming-guide",
    publishedDate: "2026-03-29",
    updatedDate: "2026-03-29",
    author: "The PickleHub Team",
    tags: ["livestream", "streaming", "guide"],
    ctaPath: "/live",
    ctaLabel: { en: "Watch Live Now", vi: "Xem trực tiếp ngay" },
    heroImage: undefined,
    titleEn: "Pickleball Live Streaming — How to Watch & Stream Pickleball Online",
    titleVi: "Trực tiếp Pickleball — Cách xem và phát sóng trực tuyến",
    metaTitleEn: "Pickleball Live Streaming 2026 | How to Watch & Stream Online Free",
    metaTitleVi: "Xem trực tiếp Pickleball 2026 | Hướng dẫn phát sóng và xem miễn phí",
    metaDescriptionEn: "Watch pickleball live streams for free. Learn how to stream your own pickleball tournament online with The Pickle Hub's free livestreaming platform.",
    metaDescriptionVi: "Xem trực tiếp pickleball miễn phí. Hướng dẫn phát sóng giải đấu pickleball trực tuyến với nền tảng livestream miễn phí của The Pickle Hub.",
  },  {
    slug: "pickleball-round-robin-generator-guide",
    publishedDate: "2025-10-10",
    updatedDate: "2026-03-27",
    author: "The PickleHub Team",
    tags: ["round-robin", "generator", "tutorial"],
    ctaPath: "/tools/quick-tables",
    ctaLabel: { en: "Generate Round Robin Now", vi: "Tạo vòng tròn ngay" },
    heroImage: undefined,
    titleEn: "Pickleball Round Robin Generator — How to Run the Perfect Round Robin Tournament",
    titleVi: "Công cụ tạo vòng tròn Pickleball — Cách tổ chức giải vòng tròn hoàn hảo",
    metaTitleEn: "Pickleball Round Robin Generator | Free Tool & Complete Guide 2026",
    metaTitleVi: "Công cụ tạo vòng tròn Pickleball | Miễn phí & Hướng dẫn đầy đủ 2026",
    metaDescriptionEn: "Free pickleball round robin generator with auto scheduling, court rotation, and live scoring. Organize a perfect round robin tournament.",
    metaDescriptionVi: "Công cụ tạo vòng tròn pickleball miễn phí với lịch tự động, xoay sân, và chấm điểm trực tiếp. Hướng dẫn tổ chức giải vòng tròn hoàn hảo.",
  },  {
    slug: "pickleball-rules-complete-guide",
    publishedDate: "2026-04-19",
    updatedDate: "2026-04-19",
    author: "Cuong Nguyen",
    tags: ["pickleball rules", "beginner", "kitchen rule", "serving", "scoring", "ppa tour asia"],
    ctaPath: "/tools/quick-tables",
    ctaLabel: { en: "Try Free Scoring Tool", vi: "Dùng thử chấm điểm miễn phí" },
    heroImage: { src: "/images/blog/pickleball-rules-complete-guide-hero.webp", alt: "Pickleball court with players at the kitchen line showing the Non-Volley Zone and serving positions under PPA Tour Asia rules" },
    titleEn: "Pickleball Rules 2026: The Complete Guide (With Asia's Hardest Calls Explained)",
    titleVi: "Luật Pickleball 2026 — Hướng dẫn đầy đủ (kèm 5 tình huống tranh cãi nhất ở châu Á)",
    metaTitleEn: "Pickleball Rules 2026 | Complete Guide with Asia's Hardest Calls Explained",
    metaTitleVi: "Luật Pickleball 2026 | Hướng dẫn đầy đủ và 5 tình huống tranh cãi nhất ở châu Á",
    metaDescriptionEn: "The 2026 pickleball rulebook simplified: serve, two-bounce, kitchen/NVZ, scoring, faults. Plus 5 disputed calls in Asian tournaments.",
    metaDescriptionVi: "Luật Pickleball 2026 đầy đủ: giao bóng, luật hai lần nảy, kitchen/NVZ, tính điểm, lỗi. Kèm 5 tình huống gây tranh cãi nhất ở các giải châu Á và cách xử lý đúng luật.",
  },  {
    slug: "pickleball-scoring-rules-guide",
    publishedDate: "2026-03-15",
    updatedDate: "2026-03-29",
    author: "The PickleHub Team",
    tags: ["scoring", "rules", "beginner"],
    ctaPath: "/tools/quick-tables",
    ctaLabel: { en: "Try Free Scoring Tool", vi: "Dùng thử chấm điểm miễn phí" },
    heroImage: undefined,
    titleEn: "Pickleball Scoring Rules Explained — Complete Guide for Beginners & Tournament Play",
    titleVi: "Luật chấm điểm Pickleball — Hướng dẫn đầy đủ cho người mới và giải đấu",
    metaTitleEn: "Pickleball Scoring Rules 2026 | Complete Beginner & Tournament Guide",
    metaTitleVi: "Luật chấm điểm Pickleball 2026 | Hướng dẫn cho người mới & giải đấu",
    metaDescriptionEn: "Learn pickleball scoring rules for singles, doubles, and tournament play. Rally scoring vs side-out explained. Free digital scoring tool included.",
    metaDescriptionVi: "Học luật chấm điểm pickleball cho đơn, đôi và giải đấu. Rally scoring vs side-out giải thích chi tiết. Công cụ chấm điểm số miễn phí.",
  },  {
    slug: "pickleball-tournament-formats-explained",
    publishedDate: "2026-03-25",
    updatedDate: "2026-03-29",
    author: "The PickleHub Team",
    tags: ["formats", "tournament", "comparison"],
    ctaPath: "/tools",
    ctaLabel: { en: "Explore All Formats", vi: "Khám phá tất cả thể thức" },
    heroImage: undefined,
    titleEn: "Pickleball Tournament Formats Explained — Which One Should You Use?",
    titleVi: "Các thể thức giải Pickleball giải thích — Nên dùng thể thức nào?",
    metaTitleEn: "Pickleball Tournament Formats Explained | Round Robin, Elimination & More",
    metaTitleVi: "Thể thức giải Pickleball giải thích | Vòng tròn, Loại trực tiếp & Khác",
    metaDescriptionEn: "Pickleball tournament formats explained: round robin, single + double elimination, MLP team match, flex. Choose the right format for your event.",
    metaDescriptionVi: "Hướng dẫn đầy đủ về thể thức giải pickleball: vòng tròn, loại trực tiếp, loại kép, MLP team match, và flex tournament. Chọn đúng thể thức cho sự kiện của bạn.",
  },  {
    slug: "ppa-tour-asia-2026-complete-guide",
    publishedDate: "2026-04-16",
    updatedDate: "2026-04-16",
    author: "The PickleHub Team",
    tags: ["ppa tour asia", "tournament", "asia", "schedule", "guide"],
    ctaPath: "/tournaments",
    ctaLabel: { en: "Browse Tournaments", vi: "Xem các giải đấu" },
    heroImage: { src: "/images/blog/ppa-tour-asia-2026-hero.webp", alt: "PPA Tour Asia 2026 professional pickleball tournament with multiple courts and packed stadium" },
    titleEn: "PPA Tour Asia 2026: Complete Schedule, Prize Money & How to Play",
    titleVi: "PPA Tour Asia 2026: Lịch thi đấu, Tiền thưởng & Cách tham gia",
    metaTitleEn: "PPA Tour Asia 2026 Schedule & Guide | All 10 Stops, Prize Money, How to Play",
    metaTitleVi: "PPA Tour Asia 2026 | Lịch thi đấu đầy đủ, Tiền thưởng, Cách tham gia",
    metaDescriptionEn: "Complete guide to PPA Tour Asia 2026 — all 10 tournament stops, $2.15M total prize money, dates, cities, and how amateurs can play alongside the pros.",
    metaDescriptionVi: "Hướng dẫn đầy đủ PPA Tour Asia 2026 — 10 chặng đấu, tổng tiền thưởng $2.15 triệu, lịch trình, địa điểm và cách VĐV nghiệp dư tham gia thi đấu cùng các pro.",
  },
  {
    slug: "tama-shimabukuro-ppa-atlanta-final-15-year-old",
    publishedDate: "2026-05-11",
    updatedDate: "2026-05-11",
    author: "Cuong Nguyen",
    tags: ["tama shimabukuro", "ppa tour", "atlanta championships", "hunter johnson", "federico staksrud", "young players", "professional pickleball", "hawaii"],
    ctaPath: "/blog/ppa-tour-asia-2026-complete-guide",
    ctaLabel: { en: "Read: PPA Tour Asia 2026 Complete Guide", vi: "Đọc tiếp: PPA Tour Asia 2026 — Hướng dẫn đầy đủ" },
    heroImage: {
      src: "/images/blog/tama-shimabukuro-atlanta-hero.webp",
      alt: "Tama Shimabukuro, the 15-year-old pickleball pro from Hawaii, at the PPA Veolia Atlanta Championships where he defeated world #1 Hunter Johnson and world #2 Federico Staksrud to reach the men's singles final — a self-taught player who started in 2023 and signed his three-year PPA Tour contract at 14"
    },
    titleEn: "Tama Shimabukuro: How a 15-Year-Old From Hawaii Took Down World #1 and #2 at PPA Atlanta",
    titleVi: "Tama Shimabukuro: 15 tuổi, hạ số 1 và số 2 thế giới, vào chung kết PPA Atlanta",
    metaTitleEn: "Tama Shimabukuro Reaches PPA Atlanta Final at 15 | Beats Hunter Johnson & Staksrud",
    metaTitleVi: "Tama Shimabukuro vào chung kết PPA Atlanta ở tuổi 15 | Hạ Hunter Johnson & Staksrud",
    metaDescriptionEn: "15-year-old Tama Shimabukuro beat world #1 Hunter Johnson and #2 Staksrud at PPA Atlanta Championships to reach the final. Self-taught Hawaii story.",
    metaDescriptionVi: "Tama Shimabukuro 15 tuổi vừa hạ số 1 thế giới Hunter Johnson và số 2 Federico Staksrud tại PPA Veolia Atlanta Championships. Câu chuyện tự học từ Hawaii.",
  },
  {
    slug: "what-is-dupr-pickleball-rating-system",
    publishedDate: "2026-05-11",
    updatedDate: "2026-05-11",
    author: "Cuong Nguyen",
    tags: ["dupr", "pickleball rating", "skill rating", "ppa tour", "mlp", "usa pickleball", "vietnam", "beginner guide"],
    ctaPath: "/blog/ppa-tour-asia-2026-complete-guide",
    ctaLabel: { en: "Read: PPA Tour Asia 2026 Complete Guide", vi: "Đọc tiếp: PPA Tour Asia 2026 — Hướng dẫn đầy đủ" },
    heroImage: {
      src: "/images/blog/dupr-pickleball-rating-hero.webp",
      alt: "Visual explainer for DUPR (Dynamic Universal Pickleball Rating), the global pickleball skill rating system on a 2.000–8.000 scale used by PPA Tour, MLP, USA Pickleball, Pickleball World Cup, and over 1 million rated players across 175 countries"
    },
    titleEn: "What Is DUPR? The Global Pickleball Rating System Explained (Part 1 of 3)",
    titleVi: "DUPR là gì? Hệ thống xếp hạng pickleball toàn cầu cho người chơi Việt Nam (Phần 1/3)",
    metaTitleEn: "What Is DUPR? Pickleball Rating System Explained | Part 1 of 3 Series",
    metaTitleVi: "DUPR là gì? Xếp hạng pickleball toàn cầu | Series 3 phần — Phần 1",
    metaDescriptionEn: "DUPR explained: the global pickleball rating used by PPA, MLP, USA Pickleball, World Cup. How it works, who runs it, why Vietnamese players need it.",
    metaDescriptionVi: "DUPR — hệ thống xếp hạng pickleball toàn cầu dùng bởi PPA Tour, MLP, USA Pickleball, Pickleball World Cup. Cách hoạt động, ai điều hành và vì sao người chơi VN cần nó.",
  },
  {
    slug: "dupr-vietnam-partnership-ta-pickleball-thepicklehub",
    publishedDate: "2026-05-13",
    updatedDate: "2026-05-13",
    author: "Cuong Nguyen",
    tags: ["dupr", "dupr vietnam", "ta pickleball", "thepicklehub", "pickleball vietnam", "partnership", "pickleball rating", "asia pickleball"],
    ctaPath: "/blog/what-is-dupr-pickleball-rating-system",
    ctaLabel: { en: "Read: What Is DUPR? The Global Rating System Explained", vi: "Đọc tiếp: DUPR là gì? Hệ thống xếp hạng pickleball toàn cầu" },
    heroImage: {
      src: "/images/blog/dupr-ta-picklehub-partnership-hero.webp",
      alt: "First step together — preliminary partnership between DUPR (Dynamic Universal Pickleball Rating), TA Pickleball, and ThePickleHub.net to bring the global pickleball rating system to the Vietnamese pickleball community"
    },
    titleEn: "DUPR x TA Pickleball x ThePickleHub: A Preliminary Partnership for Vietnamese Pickleball",
    titleVi: "DUPR x TA Pickleball x ThePickleHub: Thỏa thuận sơ bộ cho cộng đồng pickleball Việt Nam",
    metaTitleEn: "DUPR Vietnam Partnership Announced | TA Pickleball x ThePickleHub First Step",
    metaTitleVi: "DUPR Việt Nam: Thỏa thuận sơ bộ với TA Pickleball x ThePickleHub | Bước đầu tiên",
    metaDescriptionEn: "DUPR, TA Pickleball and ThePickleHub signed a preliminary deal to bring the global pickleball rating system to Vietnam — phase 1 of a 3-phase roadmap.",
    metaDescriptionVi: "DUPR, TA Pickleball và ThePickleHub vừa ký thỏa thuận sơ bộ đưa hệ thống xếp hạng pickleball toàn cầu vào Việt Nam. Bước đầu của lộ trình ba giai đoạn.",
  },
  {
    slug: "dupr-algorithm-explained-performance-vs-expectation",
    publishedDate: "2026-05-14",
    updatedDate: "2026-05-14",
    author: "Cuong Nguyen",
    tags: ["dupr", "dupr algorithm", "pickleball rating", "performance vs expectation", "reliability score", "ppa tour", "mlp", "vietnam"],
    ctaPath: "/blog/what-is-dupr-pickleball-rating-system",
    ctaLabel: { en: "Read Part 1: What Is DUPR?", vi: "Đọc Phần 1: DUPR là gì?" },
    heroImage: {
      src: "/images/blog/dupr-algorithm-performance-vs-expectation-hero.webp",
      alt: "Diagram explaining how the DUPR (Dynamic Universal Pickleball Rating) algorithm works after the July 2025 rewrite: it compares actual match score to an expected score derived from the average rating of both sides, so a player can win a match and still lose rating points if they underperformed expectation, or lose a match and still gain points if they overperformed."
    },
    titleEn: "How the DUPR Algorithm Works: Performance vs Expectation Explained (Part 2 of 3)",
    titleVi: "Thuật toán DUPR: Vì sao thắng vẫn mất điểm, thua vẫn tăng điểm? (Phần 2/3)",
    metaTitleEn: "DUPR Algorithm Explained 2025: Why You Lose Points After Winning | Part 2 of 3",
    metaTitleVi: "Thuật toán DUPR 2025 giải thích | Thắng mất điểm, thua tăng điểm — Phần 2/3",
    metaDescriptionEn: "DUPR's July 2025 algorithm: why winning can lose points and losing can gain them. Match weights, exclusion rules, reliability score. Part 2 of 3.",
    metaDescriptionVi: "DUPR thay đổi thuật toán tháng 7/2025: thắng có thể vẫn mất điểm, thua có thể vẫn tăng điểm. Performance vs Expectation, trọng số trận, Reliability Score — Phần 2/3 series DUPR.",
  },
];

export const blogSlugs: string[] = blogMetadata.map((p) => p.slug);
