// AUTO-GENERATED by scripts/gen-blog-barrel.mjs — do not edit by hand.
// Static barrel of every EN blog post, for consumers that cannot use Vite's
// import.meta.glob (Cloudflare Pages Functions / the SSR bot path).
//
// Loaders, not values, on purpose: _middleware.ts runs for EVERY request, and
// a static import list would construct all 48 post objects at worker
// startup. esbuild wraps dynamically-imported modules in lazy __esm() inits, so
// a request only pays for the one post it renders.
//
// Regenerate:  node scripts/gen-blog-barrel.mjs
import type { BlogPost } from "../types";

export const blogPostLoaders: Record<string, () => Promise<{ default: BlogPost }>> = {
  "app-tour-vs-ppa-tour-contracts-2026": () => import("./app-tour-vs-ppa-tour-contracts-2026"),
  "best-pickleball-paddles-beginners-2026": () => import("./best-pickleball-paddles-beginners-2026"),
  "best-pickleball-tournament-software-2026": () => import("./best-pickleball-tournament-software-2026"),
  "dupr-algorithm-explained-performance-vs-expectation": () => import("./dupr-algorithm-explained-performance-vs-expectation"),
  "dupr-rating-improvement-30-day-plan": () => import("./dupr-rating-improvement-30-day-plan"),
  "dupr-thepicklehub-user-guide": () => import("./dupr-thepicklehub-user-guide"),
  "dupr-vietnam-partnership-ta-pickleball-thepicklehub": () => import("./dupr-vietnam-partnership-ta-pickleball-thepicklehub"),
  "hcmc-open-2026-preview": () => import("./hcmc-open-2026-preview"),
  "how-to-create-pickleball-bracket": () => import("./how-to-create-pickleball-bracket"),
  "how-to-organize-pickleball-tournament": () => import("./how-to-organize-pickleball-tournament"),
  "how-to-play-pickleball": () => import("./how-to-play-pickleball"),
  "how-to-watch-ppa-tour-live-2026": () => import("./how-to-watch-ppa-tour-live-2026"),
  "mlp-format-explained": () => import("./mlp-format-explained"),
  "mlp-orlando-super-sunday-2026-best-game": () => import("./mlp-orlando-super-sunday-2026-best-game"),
  "mlp-vs-ppa-2026-which-tour-to-watch": () => import("./mlp-vs-ppa-2026-which-tour-to-watch"),
  "pickleball-club-management-software-comparison": () => import("./pickleball-club-management-software-comparison"),
  "pickleball-cost-vietnam-2026": () => import("./pickleball-cost-vietnam-2026"),
  "pickleball-court-dimensions-setup-guide": () => import("./pickleball-court-dimensions-setup-guide"),
  "pickleball-dink-technique-mastery": () => import("./pickleball-dink-technique-mastery"),
  "pickleball-doubles-stacking-strategy": () => import("./pickleball-doubles-stacking-strategy"),
  "pickleball-doubles-strategy-guide": () => import("./pickleball-doubles-strategy-guide"),
  "pickleball-erne-shot-tutorial": () => import("./pickleball-erne-shot-tutorial"),
  "pickleball-for-tennis-players-2026": () => import("./pickleball-for-tennis-players-2026"),
  "pickleball-live-streaming-guide": () => import("./pickleball-live-streaming-guide"),
  "pickleball-round-robin-generator-guide": () => import("./pickleball-round-robin-generator-guide"),
  "pickleball-rules-complete-guide": () => import("./pickleball-rules-complete-guide"),
  "pickleball-scoring-rules-guide": () => import("./pickleball-scoring-rules-guide"),
  "pickleball-third-shot-drop-vs-drive": () => import("./pickleball-third-shot-drop-vs-drive"),
  "pickleball-tour-wars-2023-explained": () => import("./pickleball-tour-wars-2023-explained"),
  "pickleball-tournament-budget-calculator-guide": () => import("./pickleball-tournament-budget-calculator-guide"),
  "pickleball-tournament-formats-explained": () => import("./pickleball-tournament-formats-explained"),
  "pickleball-vs-padel-vs-paddle-tennis": () => import("./pickleball-vs-padel-vs-paddle-tennis"),
  "pickleball-world-cup-2026-da-nang": () => import("./pickleball-world-cup-2026-da-nang"),
  "pickleball-world-cup-2026-da-nang-how-to-watch": () => import("./pickleball-world-cup-2026-da-nang-how-to-watch"),
  "ppa-beijing-open-2026-recap": () => import("./ppa-beijing-open-2026-recap"),
  "ppa-tour-asia-2026-complete-guide": () => import("./ppa-tour-asia-2026-complete-guide"),
  "ppa-tour-asia-2026-recap": () => import("./ppa-tour-asia-2026-recap"),
  "professional-pickleball-tours-guide-2026": () => import("./professional-pickleball-tours-guide-2026"),
  "singapore-open-2026-preview": () => import("./singapore-open-2026-preview"),
  "singapore-open-2026-recap": () => import("./singapore-open-2026-recap"),
  "tama-shimabukuro-ppa-atlanta-final-15-year-old": () => import("./tama-shimabukuro-ppa-atlanta-final-15-year-old"),
  "tournament-organizer-hub": () => import("./tournament-organizer-hub"),
  "vietnam-dupr-leaderboard-launch": () => import("./vietnam-dupr-leaderboard-launch"),
  "vietnam-hosts-ppa-tour-asia-2026": () => import("./vietnam-hosts-ppa-tour-asia-2026"),
  "vietnam-pickleball-federation-2026": () => import("./vietnam-pickleball-federation-2026"),
  "vietnam-pickleball-players-to-watch-2026": () => import("./vietnam-pickleball-players-to-watch-2026"),
  "vietnam-pickleball-tournament-calendar-2026": () => import("./vietnam-pickleball-tournament-calendar-2026"),
  "what-is-dupr-pickleball-rating-system": () => import("./what-is-dupr-pickleball-rating-system"),
};

export const blogPostSlugs = Object.keys(blogPostLoaders);

/** Load one post's module. Returns undefined for an unknown slug. */
export async function loadBlogPost(slug: string): Promise<BlogPost | undefined> {
  const loader = blogPostLoaders[slug];
  if (!loader) return undefined;
  return (await loader()).default;
}
