-- OPS-00: per-schedule cron health monitoring.
--
-- Monitored first wave:
--   * mux-sync-assets: every 4h + 2h grace
--   * dupr-sync-daily: every 24h + 2h grace
--   * DUPR rankings GitHub workflow: every 7d + 1d grace
--
-- pg_net responses are short-lived. The alert function calls
-- ops_refresh_cron_health_snapshot() every ten minutes; the function copies
-- the response fields into ops_cron_dispatches before pg_net garbage-collects
-- them. Browser roles have no access to any of these operational tables.

CREATE TABLE IF NOT EXISTS public.ops_cron_monitors (
  monitor_key               text PRIMARY KEY,
  display_name              text NOT NULL,
  source                    text NOT NULL CHECK (source IN ('pg_net', 'github_actions')),
  cron_job_name             text,
  external_identifier       text,
  expected_interval_seconds integer NOT NULL CHECK (expected_interval_seconds > 0),
  grace_seconds             integer NOT NULL CHECK (grace_seconds >= 0),
  monitoring_started_at     timestamptz NOT NULL DEFAULT now(),
  enabled                   boolean NOT NULL DEFAULT true,
  CHECK (
    (source = 'pg_net' AND cron_job_name IS NOT NULL) OR
    (source = 'github_actions' AND external_identifier IS NOT NULL)
  )
);

CREATE TABLE IF NOT EXISTS public.ops_cron_dispatches (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  monitor_key      text NOT NULL REFERENCES public.ops_cron_monitors(monitor_key) ON DELETE CASCADE,
  request_id       bigint NOT NULL,
  dispatched_at    timestamptz NOT NULL DEFAULT clock_timestamp(),
  responded_at     timestamptz,
  http_status_code integer,
  timed_out        boolean,
  transport_error  text,
  response_content text,
  UNIQUE (monitor_key, request_id)
);

CREATE INDEX IF NOT EXISTS ops_cron_dispatches_monitor_dispatched_idx
  ON public.ops_cron_dispatches (monitor_key, dispatched_at DESC);

CREATE TABLE IF NOT EXISTS public.ops_cron_alert_state (
  monitor_key         text PRIMARY KEY REFERENCES public.ops_cron_monitors(monitor_key) ON DELETE CASCADE,
  last_state          text NOT NULL CHECK (last_state IN (
    'healthy', 'pending', 'never_ran', 'stale', 'ran_failed',
    'partial_success', 'caller_auth_failed'
  )),
  incident_started_at timestamptz,
  last_alerted_at     timestamptz,
  recovered_at        timestamptz,
  last_reason         text,
  updated_at          timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.ops_cron_monitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ops_cron_dispatches ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ops_cron_alert_state ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.ops_cron_monitors FROM anon, authenticated;
REVOKE ALL ON public.ops_cron_dispatches FROM anon, authenticated;
REVOKE ALL ON public.ops_cron_alert_state FROM anon, authenticated;
GRANT SELECT ON public.ops_cron_monitors TO service_role;
GRANT SELECT, INSERT, UPDATE ON public.ops_cron_dispatches TO service_role;
GRANT SELECT, INSERT, UPDATE ON public.ops_cron_alert_state TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.ops_cron_dispatches_id_seq TO service_role;

INSERT INTO public.ops_cron_monitors (
  monitor_key,
  display_name,
  source,
  cron_job_name,
  external_identifier,
  expected_interval_seconds,
  grace_seconds
)
VALUES
  (
    'mux-sync-assets',
    'Mux asset reconciliation',
    'pg_net',
    'mux-sync-assets-every-4-hours',
    NULL,
    14400,
    7200
  ),
  (
    'dupr-sync-daily',
    'DUPR daily rating backfill',
    'pg_net',
    'dupr-sync-daily',
    NULL,
    86400,
    7200
  ),
  (
    'dupr-rankings-refresh',
    'DUPR weekly rankings refresh',
    'github_actions',
    NULL,
    'dupr-refresh.yml',
    604800,
    86400
  )
ON CONFLICT (monitor_key) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  source = EXCLUDED.source,
  cron_job_name = EXCLUDED.cron_job_name,
  external_identifier = EXCLUDED.external_identifier,
  expected_interval_seconds = EXCLUDED.expected_interval_seconds,
  grace_seconds = EXCLUDED.grace_seconds,
  enabled = true;

-- Persist any available pg_net response, then return one row per configured
-- monitor. SECURITY DEFINER is required because cron/net schemas are not
-- exposed through PostgREST. Only service_role may execute it.
CREATE OR REPLACE FUNCTION public.ops_refresh_cron_health_snapshot()
RETURNS TABLE (
  monitor_key text,
  display_name text,
  source text,
  cron_job_name text,
  external_identifier text,
  expected_interval_seconds integer,
  grace_seconds integer,
  monitoring_started_at timestamptz,
  job_exists boolean,
  job_active boolean,
  scheduler_started_at timestamptz,
  scheduler_status text,
  scheduler_message text,
  dispatched_at timestamptz,
  responded_at timestamptz,
  http_status_code integer,
  timed_out boolean,
  transport_error text,
  response_content text,
  business_error_summary text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $function$
BEGIN
  UPDATE public.ops_cron_dispatches AS dispatch
  SET
    responded_at = response.created,
    http_status_code = response.status_code,
    timed_out = response.timed_out,
    transport_error = response.error_msg,
    response_content = left(response.content, 10000)
  FROM net._http_response AS response
  WHERE response.id = dispatch.request_id
    AND dispatch.responded_at IS NULL;

  RETURN QUERY
  SELECT
    monitor.monitor_key,
    monitor.display_name,
    monitor.source,
    monitor.cron_job_name,
    monitor.external_identifier,
    monitor.expected_interval_seconds,
    monitor.grace_seconds,
    monitor.monitoring_started_at,
    (job.jobid IS NOT NULL) AS job_exists,
    job.active AS job_active,
    scheduler.start_time AS scheduler_started_at,
    scheduler.status AS scheduler_status,
    scheduler.return_message AS scheduler_message,
    dispatch.dispatched_at,
    dispatch.responded_at,
    dispatch.http_status_code,
    dispatch.timed_out,
    dispatch.transport_error,
    dispatch.response_content,
    business.error_summary AS business_error_summary
  FROM public.ops_cron_monitors AS monitor
  LEFT JOIN LATERAL (
    SELECT cron_job.jobid, cron_job.active
    FROM cron.job AS cron_job
    WHERE cron_job.jobname = monitor.cron_job_name
    LIMIT 1
  ) AS job ON true
  LEFT JOIN LATERAL (
    SELECT run.start_time, run.status, run.return_message
    FROM cron.job_run_details AS run
    WHERE run.jobid = job.jobid
    ORDER BY run.start_time DESC
    LIMIT 1
  ) AS scheduler ON true
  LEFT JOIN LATERAL (
    SELECT recorded.*
    FROM public.ops_cron_dispatches AS recorded
    WHERE recorded.monitor_key = monitor.monitor_key
    ORDER BY recorded.dispatched_at DESC
    LIMIT 1
  ) AS dispatch ON true
  LEFT JOIN LATERAL (
    SELECT sync_run.error_summary
    FROM public.dupr_sync_runs AS sync_run
    WHERE monitor.monitor_key = 'dupr-sync-daily'
      AND dispatch.dispatched_at IS NOT NULL
      AND sync_run.started_at BETWEEN
        dispatch.dispatched_at - interval '2 minutes'
        AND dispatch.dispatched_at + interval '30 minutes'
    ORDER BY abs(extract(epoch FROM sync_run.started_at - dispatch.dispatched_at))
    LIMIT 1
  ) AS business ON true
  WHERE monitor.enabled
  ORDER BY monitor.monitor_key;
END;
$function$;

REVOKE ALL ON FUNCTION public.ops_refresh_cron_health_snapshot() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.ops_refresh_cron_health_snapshot() TO service_role;

-- Install or update the monitored pg_net callers. Also move the two remaining
-- legacy callers (match-expire and auto-cancel) off plaintext cron.job secrets
-- so CRON_SECRET can be rotated at one Vault-backed control point.
DO $migration$
DECLARE
  v_command text;
  v_job_id bigint;
BEGIN
  v_command := $command$
DO $dupr_job$
DECLARE
  v_secret text;
  v_request_id bigint;
BEGIN
  SELECT decrypted_secret INTO v_secret
  FROM vault.decrypted_secrets
  WHERE name = 'cron_secret'
  LIMIT 1;

  IF v_secret IS NULL THEN
    RAISE EXCEPTION 'cron_secret is not configured';
  END IF;

  SELECT net.http_post(
    url := 'https://ajvlcamxemgbxduhiqrl.supabase.co/functions/v1/dupr-sync',
    headers := jsonb_build_object(
      'Authorization', 'Bearer ' || v_secret,
      'Content-Type', 'application/json'
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 60000
  ) INTO v_request_id;

  INSERT INTO public.ops_cron_dispatches (monitor_key, request_id)
  VALUES ('dupr-sync-daily', v_request_id);
END
$dupr_job$;
$command$;

  SELECT jobid INTO v_job_id FROM cron.job WHERE jobname = 'dupr-sync-daily' LIMIT 1;
  IF v_job_id IS NULL THEN
    PERFORM cron.schedule('dupr-sync-daily', '0 20 * * *', v_command);
  ELSE
    PERFORM cron.alter_job(job_id := v_job_id, schedule := '0 20 * * *', command := v_command, active := true);
  END IF;

  v_command := $command$
DO $mux_job$
DECLARE
  v_secret text;
  v_request_id bigint;
BEGIN
  SELECT decrypted_secret INTO v_secret
  FROM vault.decrypted_secrets
  WHERE name = 'cron_secret'
  LIMIT 1;

  IF v_secret IS NULL THEN
    RAISE EXCEPTION 'cron_secret is not configured';
  END IF;

  SELECT net.http_post(
    url := 'https://ajvlcamxemgbxduhiqrl.supabase.co/functions/v1/mux-sync-assets',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-cron-secret', v_secret
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 60000
  ) INTO v_request_id;

  INSERT INTO public.ops_cron_dispatches (monitor_key, request_id)
  VALUES ('mux-sync-assets', v_request_id);
END
$mux_job$;
$command$;

  SELECT jobid INTO v_job_id FROM cron.job WHERE jobname = 'mux-sync-assets-every-4-hours' LIMIT 1;
  IF v_job_id IS NULL THEN
    PERFORM cron.schedule('mux-sync-assets-every-4-hours', '0 */4 * * *', v_command);
  ELSE
    PERFORM cron.alter_job(job_id := v_job_id, schedule := '0 */4 * * *', command := v_command, active := true);
  END IF;

  v_command := $command$
DO $match_expire_job$
DECLARE
  v_secret text;
BEGIN
  SELECT decrypted_secret INTO v_secret
  FROM vault.decrypted_secrets
  WHERE name = 'cron_secret'
  LIMIT 1;

  IF v_secret IS NULL THEN
    RAISE EXCEPTION 'cron_secret is not configured';
  END IF;

  PERFORM net.http_post(
    url := 'https://ajvlcamxemgbxduhiqrl.supabase.co/functions/v1/match-expire',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-cron-secret', v_secret
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 30000
  );
END
$match_expire_job$;
$command$;

  SELECT jobid INTO v_job_id FROM cron.job WHERE jobname = 'match-expire-daily' LIMIT 1;
  IF v_job_id IS NULL THEN
    PERFORM cron.schedule('match-expire-daily', '0 21 * * *', v_command);
  ELSE
    PERFORM cron.alter_job(job_id := v_job_id, schedule := '0 21 * * *', command := v_command, active := true);
  END IF;

  v_command := $command$
DO $auto_cancel_job$
DECLARE
  v_secret text;
BEGIN
  SELECT decrypted_secret INTO v_secret
  FROM vault.decrypted_secrets
  WHERE name = 'cron_secret'
  LIMIT 1;

  IF v_secret IS NULL THEN
    RAISE EXCEPTION 'cron_secret is not configured';
  END IF;

  PERFORM net.http_post(
    url := 'https://ajvlcamxemgbxduhiqrl.supabase.co/functions/v1/auto-cancel-unpaid-registrations',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'x-cron-secret', v_secret
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 30000
  );
END
$auto_cancel_job$;
$command$;

  SELECT jobid INTO v_job_id FROM cron.job WHERE jobname = 'auto-cancel-unpaid-registrations' LIMIT 1;
  IF v_job_id IS NULL THEN
    PERFORM cron.schedule('auto-cancel-unpaid-registrations', '0 * * * *', v_command);
  ELSE
    PERFORM cron.alter_job(job_id := v_job_id, schedule := '0 * * * *', command := v_command, active := true);
  END IF;

  -- errors-telegram-alert is the dispatcher for both browser-error spikes and
  -- cron-health incidents. Keep the caller in source control and include the
  -- x-cron-secret header required by its fail-closed handler.
  v_command := $command$
DO $alert_job$
DECLARE
  v_anon_key text;
  v_cron_secret text;
BEGIN
  SELECT decrypted_secret INTO v_anon_key
  FROM vault.decrypted_secrets
  WHERE name = 'internal_anon_key'
  LIMIT 1;

  SELECT decrypted_secret INTO v_cron_secret
  FROM vault.decrypted_secrets
  WHERE name = 'cron_secret'
  LIMIT 1;

  IF v_anon_key IS NULL OR v_cron_secret IS NULL THEN
    RAISE EXCEPTION 'internal_anon_key or cron_secret is not configured';
  END IF;

  PERFORM net.http_post(
    url := 'https://ajvlcamxemgbxduhiqrl.supabase.co/functions/v1/errors-telegram-alert',
    headers := jsonb_build_object(
      'Content-Type', 'application/json',
      'Authorization', 'Bearer ' || v_anon_key,
      'x-cron-secret', v_cron_secret
    ),
    body := '{}'::jsonb,
    timeout_milliseconds := 30000
  );
END
$alert_job$;
$command$;

  SELECT jobid INTO v_job_id FROM cron.job WHERE jobname = 'errors-telegram-alert-10min' LIMIT 1;
  IF v_job_id IS NULL THEN
    PERFORM cron.schedule('errors-telegram-alert-10min', '*/10 * * * *', v_command);
  ELSE
    PERFORM cron.alter_job(job_id := v_job_id, schedule := '*/10 * * * *', command := v_command, active := true);
  END IF;
END;
$migration$;

NOTIFY pgrst, 'reload schema';
