-- ============================================================================
-- Social Events MVP — PR47 Live Event UX
-- ============================================================================
-- New table `social_event_matches` storing the match schedule generated by
-- the organizer (Mexicano / Round Robin) so that:
--
--   - The /su-kien/:slug/live page can render Now / Next / Standings zones
--     from a real query rather than session-local React state.
--   - Players can submit scores from their phones via the magic_token they
--     received at registration, and both teams confirm before the row
--     transitions to status='completed'.
--   - Realtime (`postgres_changes` on this table) pushes match updates to
--     every connected client during the session.
--
-- Conventions kept identical to 20260511130000 (the foundation grants
-- migration). New table here, so we add GRANTs in the SAME file rather
-- than relying on a follow-up migration — the GRANT layer is the gate
-- before RLS, missing it gives a 42501 that looks like RLS but isn't.
--
-- IDEMPOTENT: replay-safe.
-- ============================================================================

-- ─── 1. Table ───────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS public.social_event_matches (
  id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  event_id              UUID NOT NULL REFERENCES public.social_events(id) ON DELETE CASCADE,
  round                 INTEGER NOT NULL,
  court                 INTEGER NOT NULL,
  team_a_player1_id     UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  team_a_player2_id     UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  team_b_player1_id     UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  team_b_player2_id     UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  team_a_score          INTEGER,
  team_b_score          INTEGER,
  status                TEXT NOT NULL DEFAULT 'scheduled',
  confirmed_by_team_a   BOOLEAN NOT NULL DEFAULT false,
  confirmed_by_team_b   BOOLEAN NOT NULL DEFAULT false,
  winning_team          TEXT,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at            TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.social_event_matches
  DROP CONSTRAINT IF EXISTS social_event_matches_status_check;
ALTER TABLE public.social_event_matches
  ADD CONSTRAINT social_event_matches_status_check
  CHECK (status IN ('scheduled', 'in_progress', 'completed'));

ALTER TABLE public.social_event_matches
  DROP CONSTRAINT IF EXISTS social_event_matches_winning_team_check;
ALTER TABLE public.social_event_matches
  ADD CONSTRAINT social_event_matches_winning_team_check
  CHECK (winning_team IS NULL OR winning_team IN ('a', 'b'));

ALTER TABLE public.social_event_matches
  DROP CONSTRAINT IF EXISTS social_event_matches_round_positive;
ALTER TABLE public.social_event_matches
  ADD CONSTRAINT social_event_matches_round_positive
  CHECK (round >= 1 AND round <= 50);

ALTER TABLE public.social_event_matches
  DROP CONSTRAINT IF EXISTS social_event_matches_court_positive;
ALTER TABLE public.social_event_matches
  ADD CONSTRAINT social_event_matches_court_positive
  CHECK (court >= 1 AND court <= 50);

ALTER TABLE public.social_event_matches
  DROP CONSTRAINT IF EXISTS social_event_matches_score_nonneg;
ALTER TABLE public.social_event_matches
  ADD CONSTRAINT social_event_matches_score_nonneg
  CHECK (
    (team_a_score IS NULL OR team_a_score >= 0)
    AND (team_b_score IS NULL OR team_b_score >= 0)
  );

-- ─── 2. Indexes ─────────────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_social_event_matches_event_id
  ON public.social_event_matches (event_id);
CREATE INDEX IF NOT EXISTS idx_social_event_matches_event_round
  ON public.social_event_matches (event_id, round, court);
CREATE INDEX IF NOT EXISTS idx_social_event_matches_team_a_p1
  ON public.social_event_matches (team_a_player1_id)
  WHERE team_a_player1_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_social_event_matches_team_a_p2
  ON public.social_event_matches (team_a_player2_id)
  WHERE team_a_player2_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_social_event_matches_team_b_p1
  ON public.social_event_matches (team_b_player1_id)
  WHERE team_b_player1_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_social_event_matches_team_b_p2
  ON public.social_event_matches (team_b_player2_id)
  WHERE team_b_player2_id IS NOT NULL;

-- ─── 3. RLS ─────────────────────────────────────────────────────────────────

ALTER TABLE public.social_event_matches ENABLE ROW LEVEL SECURITY;

-- SELECT: anyone can read matches whose event is published+public; organizer
-- and admin see everything. Pattern mirrors event_registrations_select.
DROP POLICY IF EXISTS "social_event_matches_select" ON public.social_event_matches;
CREATE POLICY "social_event_matches_select" ON public.social_event_matches
  FOR SELECT
  USING (
    public.has_role(auth.uid(), 'admin'::public.app_role)
    OR EXISTS (
      SELECT 1
      FROM public.social_events e
      WHERE e.id = social_event_matches.event_id
        AND (
          e.created_by = auth.uid()
          OR (e.status = 'published' AND e.visibility = 'public')
        )
    )
  );

-- INSERT: organizer of the event or admin only. Players cannot create
-- matches — the schedule is authored by the organizer via the matchmaking
-- page's "Save to event" action.
DROP POLICY IF EXISTS "social_event_matches_insert_organizer" ON public.social_event_matches;
CREATE POLICY "social_event_matches_insert_organizer" ON public.social_event_matches
  FOR INSERT
  WITH CHECK (
    public.has_role(auth.uid(), 'admin'::public.app_role)
    OR EXISTS (
      SELECT 1
      FROM public.social_events e
      WHERE e.id = social_event_matches.event_id
        AND e.created_by = auth.uid()
    )
  );

-- UPDATE: organizer / admin OR one of the 4 players on the match (so
-- authenticated players can submit scores directly). Guest score-submission
-- via magic_token is handled by the submit-match-score edge function using
-- the service-role key and bypasses this policy entirely.
DROP POLICY IF EXISTS "social_event_matches_update" ON public.social_event_matches;
CREATE POLICY "social_event_matches_update" ON public.social_event_matches
  FOR UPDATE
  USING (
    public.has_role(auth.uid(), 'admin'::public.app_role)
    OR auth.uid() = team_a_player1_id
    OR auth.uid() = team_a_player2_id
    OR auth.uid() = team_b_player1_id
    OR auth.uid() = team_b_player2_id
    OR EXISTS (
      SELECT 1
      FROM public.social_events e
      WHERE e.id = social_event_matches.event_id
        AND e.created_by = auth.uid()
    )
  )
  WITH CHECK (
    public.has_role(auth.uid(), 'admin'::public.app_role)
    OR auth.uid() = team_a_player1_id
    OR auth.uid() = team_a_player2_id
    OR auth.uid() = team_b_player1_id
    OR auth.uid() = team_b_player2_id
    OR EXISTS (
      SELECT 1
      FROM public.social_events e
      WHERE e.id = social_event_matches.event_id
        AND e.created_by = auth.uid()
    )
  );

-- DELETE: organizer / admin only. Used when re-generating the schedule.
DROP POLICY IF EXISTS "social_event_matches_delete_organizer" ON public.social_event_matches;
CREATE POLICY "social_event_matches_delete_organizer" ON public.social_event_matches
  FOR DELETE
  USING (
    public.has_role(auth.uid(), 'admin'::public.app_role)
    OR EXISTS (
      SELECT 1
      FROM public.social_events e
      WHERE e.id = social_event_matches.event_id
        AND e.created_by = auth.uid()
    )
  );

-- ─── 4. GRANTs — gate BEFORE RLS, missing them surfaces as 42501 ────────────

GRANT SELECT                         ON public.social_event_matches TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.social_event_matches TO authenticated;

-- ─── 5. updated_at trigger ──────────────────────────────────────────────────

DROP TRIGGER IF EXISTS trg_social_event_matches_touch_updated_at ON public.social_event_matches;
CREATE TRIGGER trg_social_event_matches_touch_updated_at
  BEFORE UPDATE ON public.social_event_matches
  FOR EACH ROW
  EXECUTE FUNCTION public.tg_social_events_touch_updated_at();

-- ─── 6. Realtime publication ────────────────────────────────────────────────
-- Wrap in DO block so the migration is idempotent — ALTER PUBLICATION
-- ADD TABLE throws when the table is already a member.

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE pubname = 'supabase_realtime'
      AND schemaname = 'public'
      AND tablename = 'social_event_matches'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.social_event_matches;
  END IF;
END $$;

-- ─── 7. Comment ─────────────────────────────────────────────────────────────

COMMENT ON TABLE public.social_event_matches IS
  'Per-event Mexicano / Round Robin match schedule. Organizer authors via /su-kien/:slug/xep-cap. Players submit scores from /su-kien/:slug/live (authed via auth.uid() OR guest via magic_token through submit-match-score edge fn). Realtime publication on. See migrations/20260512100000.';
